### ISSUE TITLE
MLZ: Firewall logs - add FW diagnostic settings to firewall deployment

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#1003]
## Description

View diagnostic settings on FW - diag settings not enabled 

1.  View diagnostic settings on FW - diag settings not enabled 

## Expected behavior

diag settings enabled on AFW

## Actual behavior

diag settings are not enabled on AFW

## Screenshots
![image](https://github.com/Azure/missionlz/assets/34066455/602363a4-20b1-480f-86cc-a669ea32d02d)

## Additional context

Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.):

**Comment by sedmonds22** [comment]
The Application Rule, Network Rule, and DNS Proxy Categories are enabled in the Diagnostic Settings. The logs are configured to be sent to the defined LAW and archiving with the defined storage account is also enabled.

![Image](https://github.com/Azure/missionlz/assets/104444784/2838b14a-aecb-43f1-ab1d-8700a587c384)
