### ISSUE TITLE
AVD Add-On: Add ArcGIS workload types to UI

### ISSUE THREAD

**Issue by jamasten** [Azure/missionlz#1016]
![image](https://github.com/Azure/missionlz/assets/61800683/b6b6d871-a199-447d-8d65-53c2fad58699)

https://pro.arcgis.com/en/pro-app/latest/get-started/arcgis-pro-system-requirements.htm

**Comment by jamasten** [comment]
@Borg-GitHub any updates from ESRI on the recommendations for the VM sizes between personal and pooled host pools?

**Comment by Borg-GitHub** [comment]
VM Type		Category 
NV4as		Light
NV8as		Light
NV16as		Light/Medium
NC4as_T4	Medium
NC8as_T4	Medium/Heavy
NC16as_T4	Heavy
NV6ads_A10	Medium/Heavy
NV12ads_A10	Heavy
NV18ads_A10	Heavy
