### ISSUE TITLE
InvalidPrivateDnsZoneIds

### ISSUE THREAD

**Issue by techdawg70** [Azure/missionlz#1029]
## Benefit/Result/Outcome

Unable to deploy AVD add-on post MLZ deployment.

## Description

I received the following error message when trying to deploy.

 "status": "Failed",
    "error": {
        "code": "InvalidPrivateDnsZoneIds",
        "message": "Private Dns Zone group /subscriptions/<subscriptionID>/resourceGroups/<rg-management-name>/providers/Microsoft.Network/privateEndpoints/<pe-kv>/privateDnsZoneGroups/<0-kv> has invalid private dns zone ids .",
        "details": []

## Acceptance Criteria
Successful deployment
-  
-

**Comment by jamasten** [comment]
@techdawg70 I'm going to close this issue since the issue appeared to be an old deployment of MLZ that was missing the private DNS zones. Please feel free to reopen if that is not the case.
