### ISSUE TITLE
"Encryption at Host" RP not enabled by default.  

### ISSUE THREAD

**Issue by sergio-re** [Azure/missionlz#1036]
## Description
When deploying Windows and Linux VMs for remote access (jump boxes), deployment fails because the Encryption at Host Resource Provider is not enabled by default. 
Recommend enabling the RP with the deployment or marking it as a pre-requisite.

## Steps to Reproduce
Deployed VM on a new subscription, Encryption at Host Resource Provider is not enabled by default, so when deploying the LZ with Windows and Linux VMs, deployment fails.
 
N/A

## Expected behavior
Windows and Linux machines deploying w/o issue.

## Actual behavior
VM deployments fail

## Additional context

Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.):

**Comment by jamasten** [comment]
This prerequisite is already documented: https://github.com/Azure/missionlz/blob/main/docs/deployment-guide-bicep.md
