### ISSUE TITLE
Apply_tf.sh fails when targeting 'usgovtexas' in Azure Gov

### ISSUE THREAD

**Issue by sstjean** [Azure/missionlz#107]
**Description**
When the user targets their deployment to the 'usgovtexas' region in Azure Government, an error is thrown during the creation of the Log Analytics workspace.

**Steps to Reproduce**
1. Setup your global.tfvars so it points to the US Gov Texas region 
```
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#################################
# Global configuration values
#################################

tf_environment      ="usgovernment" # https://www.terraform.io/docs/language/settings/backends/azurerm.html#environment

mlz_cloud           ="AzureUSGovernment" # e.g. "AzureCloud" or "AzureUSGovernment", etc
mlz_tenantid        ="<< Your TenantId HERE >>"
mlz_metadatahost    ="management.azure.us" # e.g. "management.azure.com" or "management.usgovcloudapi.net"
mlz_location        ="usgovtexas" # e.g. "eastus", "usgovvirginia", etc
```
2. Run ```apply_tf.sh```

**Expected behavior**
A message appears letting the user know that US Gov Texas isn't supported.

**Actual behavior**
The saca hub deployment fails with the following error and the code performs 4 more retries, all failing the same way.

```
Error: operationalinsights.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LocationNotAvailableForResourceType" Message="The provided location 'usgovtexas' is not available for resource type 'Microsoft.OperationalInsights/workspaces'. List of available regions for the resource type is 'usgovvirginia,usgovarizona'."

  on ../../modules/hub/main.tf line 24, in resource "azurerm_log_analytics_workspace" "loganalytics":
  24: resource "azurerm_log_analytics_workspace" "loganalytics" {
```

**Screenshots**

![image](https://user-images.githubusercontent.com/7573322/112496290-00ce6a00-8d5b-11eb-9618-abcaa3b81987.png)

**Additional context**
Operating System:  Windows 10 with WSL (Ubuntu 20.04)
Terraform Version:
Cloud (public, Azure Government, etc.): Azure Government

**Comment by brooke-hamilton** [comment]
This fix for this is part of #299
