### ISSUE TITLE
Update command-line-deployment in src/docs to pass correct options to  apply_terraform.sh

### ISSUE THREAD

**Issue by shannawaz** [Azure/missionlz#108]
Update command-line-deployment in src/doc to pass correct options to  apply_terraform.sh

3rd argument is missing from  command below. Same for tier-1 

```bash
src/scripts/apply_terraform.sh \
  src/core/globals.tfvars \
  src/core/tier-0
```

**Comment by brooke-hamilton** [comment]
Closing - this issue was fixed and merged with PR 109.
