### ISSUE TITLE
Set parameter "auto_approve" defaults value to "N" in apply_terraform.sh

### ISSUE THREAD

**Issue by shannawaz** [Azure/missionlz#110]
**Is your feature request related to a problem? Please describe.**
Set parameter "auto_approve" defaults value to "N" in apply_terraform.sh. 

Customer can choose  Y if needed.  Terraform destroys infrastructure when config values are changed. Customer should be aware of those destroy and make correct decision

**Comment by brooke-hamilton** [comment]
Fixed
