### ISSUE TITLE
Apply_tf.sh fails in Azure Gov because Azure Firewall Premium not supported  

### ISSUE THREAD

**Issue by sstjean** [Azure/missionlz#111]
**Description**
When running MLZ in Azure Government, the ```apply_tf.sh``` script fails during SACA Hub creation because Azure Gov Virginia isn't a supported region for Azure Firewall Premium.

**Steps to Reproduce**
1. Run ```apply_tf.sh``` against the ```usgovvirginia``` region of Azure Government.
2. 

**Expected behavior**
When first run, the user is notified that they are deploying to an unsupported region.  Also would expect this to be called out in the docs.

**Actual behavior**
The deployment fails with an error telling the user that Firewall Premium is not available in the selected region. 

**Screenshots**

**Additional context**
Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.): Azure Gov

**Comment by brooke-hamilton** [comment]
The ideal fix for this will be to allow for a graceful fallback when deploying in a cloud that doesn't support Azure Firewall Premium.
