### ISSUE TITLE
Enable forced tunneling by default

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#117]
**Benefit/Result/Outcome**  
Have forced tunneling set up by default so that it does not have to be configured manually.

**Description**
Forced tunneling is an option when setting up the firewall. Set forced tunneling to be the default, which adds the ability to configure a management subnet, which can be the next /26 IP range.

This could be an optional setting, however, as an opinionated architecture, we should set this and allow users to change it by modifying the TF configuration. In other words, this is not an option on the command line.

**Acceptance Criteria**
- Forced tunneling is set up on the firewall
- A management subnet is created at the next /26 IP range

**Comment by sstjean** [comment]
Some documentation for Forced Tunneling in Azure Firewall:  https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling#:~:text=By%20default%2C%20forced%20tunneling%20isn%27t%20allowed%20on%20Azure,Service%20Management%20traffic%20is%20separated%20from%20customer%20traffic.
