### ISSUE TITLE
Additional Azure Firewall settings

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#119]
**Benefit/Result/Outcome**  
These settings enhance security

**Description**
Set the following settings on Azure Firewall:
~~IDPS = Alert~~
Threat Intelligence = Alert

**Acceptance Criteria**
- ~~IDPS = Alert~~
- A firewall policy is created and associated to the firewall.
- Threat Intelligence = Alert

> NOTE: The IDPS=Alert firewall policy setting will be implemented as part of a separate issue because at this time the Terraform Azure RM provider does not have support for this setting.

**Comment by johnsblevins** [comment]
Maybe consider Deny for this setting by default.  That is the most secure configuration and then whitelist ips/ranges as needed to bypass.
