### ISSUE TITLE
setup_ezdeploy.sh attempts to set the role assignment on same sub multiple times

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/missionlz#120]
**Description**
When running the setup_ezdeploy.sh script it attempts to assign the contributor role to the Service Principal it creates on the subscription for each tier even if the same sub is used for all tiers. 

**Steps to Reproduce**
1. Run setup_ezdeploy.sh using a single subscription for each tier

**Expected behavior**
setup_ezdeploy.sh should determine how many unique subs were entered and only attempt to assign the role once for each unique sub

**Actual behavior**
Attempts to assign role to each sub

**Comment by brooke-hamilton** [comment]
@Phydeauxman what is the impact of setting the same role multiple times on a single sub?

For a fix, how about using the AZ CLI to check the role assignments to see if the contributor role is already assigned, and skip the assignment if it's already there?

**Comment by Phydeauxman** [comment]
@brooke-hamilton no harm in attempting to set it more than once but we had already cleaned this up in the manual execution scripting. Going to add the code we created for that to the setup_ezdeploy.sh script.
