### ISSUE TITLE
Update documentation file "command-line-deployment.md" to run apply for saca_hub before any tier run.

### ISSUE THREAD

**Issue by shannawaz** [Azure/missionlz#123]
Received following error  when apply is run directly on tier-0.

Error: Resource Group "saca_shnawa_rg" was not found. The value is taken from this file. I see it created resource group for saca hub rg-tf-sacahub-shnawaagdev1. 

Solution - Assuming saca hub is optional, Include following  command in documentation. Otherwise a code change is required.

 src/scripts/apply_terraform.sh   src/core/globals.tfvars   src/core/saca-hub saca-hub.tfvars

**Comment by brooke-hamilton** [comment]
Closed because related PR has been merged to main
