### ISSUE TITLE
Add *tfvars.example file along with currently provided *.sample file.

### ISSUE THREAD

**Issue by shannawaz** [Azure/missionlz#125]
As a customer,  an example file for configuration  will make it easier to provide appropriate values . Otherwise the customer will have to research terraform modules to provide appropriate values.

**Comment by glennmusa** [comment]
I think we've changed direction to preferring defaults in the variables.tf for modules, no? I wonder what value the `*.tfvars.sample` files have any longer.

**Comment by brooke-hamilton** [comment]
I'm closing this as OBE because of design changes in how we are structuring the Terraform, but please re-open if we need to address it again.
