### ISSUE TITLE
Cleanup saca-hub.tfvars.sample to remove variables not used.

### ISSUE THREAD

**Issue by shannawaz** [Azure/missionlz#126]
The following variables in saca-hub.tfvars.sample  is causing  multiple warning messages.  Please remove.

tier0_rgname       = "{TIER0_RGNAME}"
tier0_vnetname     = "{TIER0_VNETNAME}"
tier1_rgname       = "{TIER1_RGNAME}"
tier1_vnetname     = "{TIER1_VNETNAME}"
tier2_rgname       = "{TIER2_RGNAME}"
tier2_vnetname     = "{TIER2_VNETNAME}"

Warning: Value for undeclared variable

The root module does not declare a variable named "tier1_rgname" but a value
was found in file
"/home/shnawa/mlz/d0328/missionlz/src/core/saca-hub/saca-hub.tfvars". To use
this value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.

**Comment by glennmusa** [comment]
This will be addressed by currently planned work. Will link to the PR when it merges to main.

**Comment by brooke-hamilton** [comment]
#228 will fix this issue. Thanks @shannawaz for the bug report. 💯
