### ISSUE TITLE
Source Log Analytics Workspace ID from the hub instead of referencing it by name and Move SACA Hub Log Analytics workspace to Tier 1

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#128]
**Benefit/Result/Outcome**  
Today you have to win the lottery and get a unique Log Analytics Workspace name from your variables files. Then, we use that name to query for a Log Analytics Workspace resource and provide that resource ID to the Tier N configurations.

Enable role separation by having log analytics work done in Tier 1. (From issue #90.)

**Description**
Instead, I should know that MLZ is going to generate a valid name for me when the Log Analytics Workspace is created at the hub, and then import that state into Tier N so that I have a reference Workspace instead of querying for one.

The current Log Analytics workspace is deployed to the SACA hub. Move to T1. (From issue #90.)

Log Analytics Workspace names must be globally unique. (From original issue #26.)

**Acceptance Criteria**
- Tier 0 - 2 reference the output of Hub Log Analytics Workspace creation
- Hub outputs the Log Analytics Workspace and resource ID
- Use the random provider when creating the log analytics workspace in the `hub` module (from issue #26) to ensure uniqueness
- A log analytics workspace is deployed to T1. (From issue #90)
- Existing logs are forwarded to the T1 LA workspace. (From issue #90)

**Comment by brooke-hamilton** [comment]
We should consider #90 when doing this work - if we move the workspace to Tier 1 how will that affect this?

**Comment by brooke-hamilton** [comment]
Based on team planning output, I combined issues #90 and #26 into this issue and closed those issues.
