### ISSUE TITLE
Quick Deploy - RG names are very similar and it's confusing

### ISSUE THREAD

**Issue by sstjean** [Azure/missionlz#150]
**Is your feature request related to a problem? Please describe.**
When you deploy MLZ using ```deploy.sh```, it creates resource groups for the terraform state as well as for the actual landing zone tiers.  The names that are generated are very similar and could be confusing to users, especially when scanning the list of resource groups.  

![image](https://user-images.githubusercontent.com/7573322/114434829-75920880-9b91-11eb-9d89-1af607cf8d4e.png)

**Describe the solution you'd like**
I think making the naming a bit more verbose would clarify issues.  Instead of the current naming, maybe spell out 'terraform' or 'tfstate' in the RG, such as ```rg-terraform-tier1-mlz-12345678``` or ```rg-tfstate-tier1-mlz12345678```

**Describe alternatives you've considered**
Considered tagging, but the default behavior of the portal isn't to show tags or group by tags, so that would take more steps and Azure knowledge to delineate the different groups of RGs.

**Additional context**
See above

**Comment by brooke-hamilton** [comment]
Merged to main
