### ISSUE TITLE
Incorrect defaults for non-commercial clouds

### ISSUE THREAD

**Issue by bspender** [Azure/missionlz#170]
The deployment scripts have a default of [tf_environment] public and [location] EastUS. If a user correctly logs into Azure CLI and specifies a non-commercial cloud (e.g. AzureUSGovernment), but does not specify an environment or location, the deployment will provision a service principal and then fail on attempts to deploy resources into the default EastUS.

**Steps to Reproduce**
1. Log into a non-commercial tenant:
    az cloud set -n AzureUSGovernment
    az login
2. Start a deployment without specifying the environment and location (which default to public and eastus)
    src/deploy.sh -s {your_subscription_id}  #without specifying the -tf_environment or -location parameter

**Expected behavior**
The deployment scripts should [reasonably] check if the configuration options are valid before creating any resources. For example, run (az account list-locations) and check that the set location is in this list. Also, could check the output of (az account show --query "environmentName" --output tsv) and conditionally set the default environment and location based on the environment (e.g. if "AzureCloud", use "EastUS" ...if "AzureUSGovernment", use "USGovVirginia")

**Actual behavior**
The deployment script proceeds, creates the service principal, then fails when attempting to create resources because the "EastUS" is not a valid Azure location

**Screenshots**

**Additional context**
Operating System: n/a
Terraform Version: n/a
Cloud: non-public clouds such as Azure Government, etc

**Comment by glennmusa** [comment]
@bspender while there could be some effort to figure out hero regions for the other clouds, in the meantime #174 has been merged that notifies a user defaults are used, informs them how to override them, and will validate for valid pairings between AzureCloud and AzureUsGovernment 👍

**Comment by brooke-hamilton** [comment]
@bspender are there additional fixes you think we should do in addition to what was done in #174 that @glennmusa referenced in the previous comment?

**Comment by bspender** [comment]
That seems sufficient - appreciate the work here. You good if I close this?

**Comment by brooke-hamilton** [comment]
Yes, thank you!
