### ISSUE TITLE
Resource cleanup was incomplete

### ISSUE THREAD

**Issue by jjansen23** [Azure/missionlz#179]
The cleanup.sh script executed but did not remove all the resources

1. After deploying missionlz, using cloud shell 
2. /home/yourusername/missionlz/src/clean.sh -z mlzxxxxxxxxx (eg mlz1619454241)

**Expected behavior**
Expected ALL the resources to be removed

**Actual behavior**
The resources were not removed

**Screenshots**
Manually deleted resources - no screen shot

**Additional context**
Operating System: Ubuntu
Terraform Version:0.15.0
Cloud (public, Azure Government, etc.): public

**Comment by glennmusa** [comment]
Thanks for logging a bug @jjansen23! Can you let us know which resources were not removed?

**Comment by brooke-hamilton** [comment]
I encountered the same thing - I used Azure cloud shell for the deployment and deployed everything into the same public Azure subscription. The hub resource group was not removed, and I believe the Terraform state rgs remained as well.

**Comment by glennmusa** [comment]
Thanks for the details. As a base test, just ran this on the .devcontainer in the repository without issue. I'll give it a go on Cloud Shell logging to a file to see where things go wrong.

**Comment by glennmusa** [comment]
I was able to successfully deploy and clean from the latest main this morning.

Can you try logging to a file and sharing with the team offline?

Here's how you can write to a file with `2>&1` and `tee`:

```plaintext
az account set -s {my_sub_id}
git clone https://github.com/azure/missionlz
missionlz/src/deploy.sh -s {my_sub_id} -z {your_mlz_env_name} 2>&1 | tee deploy_log.txt
[...some time later]
missionlz/src/clean.sh -z {your_mlz_env_name} 2>&1 | tee clean_log.txt
```

and to download via cloudshell:

![image](https://user-images.githubusercontent.com/4622125/116266147-7a39ed80-a749-11eb-83a4-b4b0a88992e6.png)

**Comment by jjansen23** [comment]
@Glenn, Tank you for the input and thorough explianation.

I deployed successfully and ran the clean script and it cleaned all the resources.
Please see attached output files as requested.

I would be this under a false positive as we had 2 successful runs (clean script) without any issue.
Do we go ahead and close this bug report ?
[deploy_log.txt](https://github.com/Azure/missionlz/files/6386513/deploy_log.txt)
[clean_log.txt](https://github.com/Azure/missionlz/files/6386514/clean_log.txt)

**Comment by glennmusa** [comment]
Glad to hear it! I'm okay with closing this if you are. @brooke-hamilton do you still run into the issues Jerome described?

**Comment by jjansen23** [comment]
I am good to close it as well. When @brooke-hamilton confirms he is okay, then I will close it.
