### ISSUE TITLE
Test for permissions to add RBAC roles on hub and spoke subscriptions and fail before resources are created

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#183]
**Benefit/Result/Outcome**  
Today we validate that the MLZ configuration subscription exists in the active cloud, the desired location exists in the active subscription, and that the azurerm terraform environment matches the active cloud.

But, an end-user could get into a scenario where they specify a Hub, T0, T1, and/or T2 subscription they do not have the privileges to add an RBAC assignment to and, with today's automation, we wouldn't know until resources are already created leaving the deployment in a half-done state.

**Description**
We should prevent execution of MLZ configuration setup if the contextual CLI user doesn't have permissions to update RBAC for the supplied subscriptions.

**Acceptance Criteria**
- Test the subscriptions passed by argument for role assignment authz
- Fail before creating any resources with a helpful error message

**Comment by brooke-hamilton** [comment]
@glennmusa I think this is OBE for Bicep and we can close the backlog item. Please reply back if I'm wrong. 😄
