### ISSUE TITLE
Roll-back changes on deployment failure

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#185]
**Is your feature request related to a problem? Please describe.**

If I don't make it all the way through a deployment, I don't get the prompt for how to clean things up.

If I don't make it all the way through terraform deployment, the clean up script will exit before cleaning up MLZ resources.

**Describe the solution you'd like**

If I don't make it all the way through a deployment, MLZ is smart enough to "roll back" everything it actually did deploy and notify me that it succeeded or didn't.

**Describe alternatives you've considered**

Manual cleanup via the Portal

**Additional context**

Sometimes deployments made from Terraform and manually deleted via ARM/Portal can cause odd behaviors (namely Log Analytics Workspaces and Azure Monitor Diagnostic Logs)

**Comment by brooke-hamilton** [comment]
Let's take another look at this after completing #228.

**Comment by glennmusa** [comment]
@brooke-hamilton removed this from 07-20 scope as it could be OBE by the clean.sh scripts, ping me if you'd like to discuss.
