### ISSUE TITLE
UI deployments fail

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#191]
**Description**
Currently the UI returns two distinct errors:

1) unsupported argument when attempting to deploy (we now source the Azure Resource Manager metadata host endpoint instead of passing it by argument)
2) terraform azurerm provider mismatch error (hosted container builds 2.55, terraform source depends on 2.55 -- yet getting an error about 2.50)

**Steps to Reproduce**
1. deploy the UI
2. click 'Execute Terraform'

**Expected behavior**
The terraform is deployed successfully.

**Actual behavior**
The terraform deployment never begins.

**Screenshots**
![image](https://user-images.githubusercontent.com/4622125/117160540-2f465880-ad8f-11eb-8506-0349b7e6ff85.png)

**Comment by glennmusa** [comment]
This occurs because the machine I built the Dockerimage from to deploy the front end app instance had an existing `/.terraform` directory and a `.terraform.lock.hcl`. 

That directory and that files were packaged up by previous deployments on the machine (see https://www.terraform.io/docs/language/dependency-lock.html#lock-file-location) and should probably be checked-for/purged before creating the image that gets hosted.

**Comment by johnsblevins** [comment]
Thanks!  I had the same issue.

**Comment by glennmusa** [comment]
@johnsblevins this should be fixed now
