### ISSUE TITLE
Add Firewall Management Subnet to Support Forced Routing Scenario

### ISSUE THREAD

**Issue by johnsblevins** [Azure/missionlz#195]
Many customers want to force route traffic back onprem or through another firewall before going out to the internet.  See https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling for details on configuration.

**Comment by glennmusa** [comment]
Thanks for the enhancement suggestions @johnsblevins! This is currently tracked at #117 -- going to close this and track development and discussion there.
