### ISSUE TITLE
Enable Traffic Analytics and V2 Logs for NSG Flow Log Capture

### ISSUE THREAD

**Issue by johnsblevins** [Azure/missionlz#196]
Currently NSG flow logs are captured to storage accounts but not to the Log Analytics Workspace as part of the traffic Analytics/Network Watcher Solution.  In addition, only NSG Flow Logs are set to V1 instead of V2.

**Comment by brooke-hamilton** [comment]
@glennmusa will create an issue for this and add to our backlog.

**Comment by glennmusa** [comment]
Tracking at #203
