### ISSUE TITLE
Suggest Centralized Log Analytics Workspace in Management Tier for Log Consolidation and Sentinel Enablement

### ISSUE THREAD

**Issue by johnsblevins** [Azure/missionlz#197]
Suggest moving log analytics workspace out of saca hub grouping to separate management Tier for future consolidation of all log sources (not just Azure Firewall and Net Flow/NSG logs).  Also consider adding the "Security" Solution (Sentinel) out of the box.

**Comment by brooke-hamilton** [comment]
Scope for this issue is now part of #128 and #256. @johnsblevins thank you for this feedback.
