### ISSUE TITLE
Allow SSL Configuration Option for User Interface Deployment Site

### ISSUE THREAD

**Issue by johnsblevins** [Azure/missionlz#198]
Allow for cert upload and certificate binding for the User Interface Deployment.

**Comment by brooke-hamilton** [comment]
@johnblevins can you give us an example of the use case? Are there times when the default azurewebsites.net cert is not wanted?

**Comment by brooke-hamilton** [comment]
@johnsblevins, if we update the deployment to use the SSL cert included with *.azurewebsites.net, will that meet the need? I am thinking that should be the default. Maybe we can also provide a way for a user's cert to be uploaded as well.

**Comment by brooke-hamilton** [comment]
Closing as OBE
