### ISSUE TITLE
.devcontainer errors on build with "failed to create symbolic link '/usr/bin/pip': File exists"

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#207]
**Description**
Users cannot build a container with the .devcontainer 

**Steps to Reproduce**
1. clone the repo and re-open in container 
2. or create a codespace from main

**Expected behavior**
A container is built and you have the tools you need to develop

**Actual behavior**
The container fails to build, erroring out at this block: https://github.com/Azure/missionlz/blob/main/.devcontainer/Dockerfile#L28-L33

**Comment by brooke-hamilton** [comment]
Until we get a fix checked in, a workaround is to edit the `Dockerfile` to remove the line that creates a symbolic link for `pip`.

```DOCKER
# Install Python 3
RUN apt-get update \
    && apt-get install -y \
    python3 \
    python3-pip \
    && ln -s /usr/bin/python3 /usr/bin/python
    # && ln -s /usr/bin/pip3 /usr/bin/pip --this line is removed because it causes a build error
```
