### ISSUE TITLE
Some script to clean up UI deployments

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#214]
**Is your feature request related to a problem? Please describe.**
After I deploy the UI, I have to manually clean up resources, the Service Principal, and App Registration

**Describe the solution you'd like**
It'd be nice if I had some automation to clean up all those things for me

**Describe alternatives you've considered**
Expand on clean.sh and create a clean_ui.sh that performs something similar

**Additional context**
Today, the deployment tags should cleanup the ACR and Container Instance, but the front-end's App Registration to permit user login will be orphaned.

**Comment by glennmusa** [comment]
This is still valid, let's plan work in the future

**Comment by brooke-hamilton** [comment]
Closing as OBE
