### ISSUE TITLE
Document what needs to be POAM'd if Firewall Standard is used instead of Premium

### ISSUE THREAD

**Issue by sstjean** [Azure/missionlz#240]
**Benefit/Result/Outcome**  
As an MLZ user in MAG or an Air-Gapped cloud, I need to know which SCCA controls aren't implemented under Firewall Standard so that I can submit a POAM for air-cover while waiting for Firewall Premium to be deployed/approved. 

**Description**
There is going to be a period in which FW Premium isn't available in some Azure environments, but the user of MLZ will still want to deploy.  They will need to understand the controls delta between Standard and Premium so they can add additional Azure resources to fill the gap or submit a POAM to bridge the roll-out/GA timeline.

**Acceptance Criteria**
- A clear document of which SCCA controls are covered by FW Premium vs. FW Standard
- A clear document on how to upgrade an existing MLZ FW from Standard to Premium when it becomes available in an Azure Cloud.

**Comment by jamasten** [comment]
Premium is available in Fairfax and no need POAM.
