### ISSUE TITLE
Document Azure CLI pre-reqs for air-gapped clouds

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#242]
**Description**
If you'd like to use MLZ, you must be able to login to Azure CLI. To login to Azure CLI in an air-gapped cloud there are environment variables you must set on the machine you're executing commands from.

**Acceptance Criteria**
- Point to documentation on how to set `arm_cloud_metadata_url` to the metadata host URL including the API version
- Point to documentation on how to get the metadata host URL including the API version
- Point to documentation on other air-gapped cloud Azure CLI dependencies and how to source those expected values

**Comment by jjansen23** [comment]
Documentation on how to set the arm_cloud_metadata_url is located in the mlz container on the Iron Bank repository at https://repo1.dso.mil/dsop/microsoft/azure/mission-landing-zone/-/blob/development/README.md
It follows the pattern: export ARM_CLOUD_METADATA_URL=<metadata_url_for_target_cloud>

**Comment by jjansen23** [comment]
The following list of end-points are available internally to MSFT employees:
https://msazure.visualstudio.com/One/_wiki/wikis/One.wiki/43658/Endpoints
