### ISSUE TITLE
Mission LZ UI Deployment - Execute Terraform Button

### ISSUE THREAD

**Issue by jjansen23** [Azure/missionlz#246]
**Description**
When using MissionLZ UI to deploy the landing zone, it is not clear which "Execute Terraform" button to click in order to launch the deployment.

**Steps to Reproduce**
1.  From the root folder of the missionlz repo, run the following command: ./src/scripts/deploy_ui.sh -s <subscription_id>
2. Once the deployment is completed, follow the link that would like like the following:   http://mlzmlz1623239837dnsd8f20d9f.eastus.azurecontainer.io - This link was deleted (so clicking will render an error)
3. Login in with Microsoft credentials

**Expected behavior**
The "Execute Terraform" button, should only be available and active on the actual tab (saca-hub) that launches the missionlz deployment. 

**Actual behavior**
Clicking  "Execute Terraform" on any of the other tabs such as globals, tier-0,tier-1,tier-2,tier-3 does not appear to do anything but render a black box. No deployment is generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/7325410/121384503-535d0280-c916-11eb-94f0-0c3008129fe6.png)

**Additional context**
Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.):

**Comment by brooke-hamilton** [comment]
I'm closing this as OBE - we will pause on UI development while we explore the ability to deploy from the Azure portal.
