### ISSUE TITLE
Log Analytics Workspace names must be globally unique

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#26]
**Description**

Log Analytics Workspace names must be globally unique

**Acceptance Criteria**
- Use the random provider when creating the log analytics workspace in the `hub` module

**Comment by glennmusa** [comment]
@shannawaz and I talked about this specific issue and he volunteered to bring in the hub as a provider for the other configurations and reference the created log analytics workspace ID from there so that is can be generated randomly.

**Comment by brooke-hamilton** [comment]
This is related to #90 and #128.

**Comment by brooke-hamilton** [comment]
Closing because I moved the scope of this issue into #128.
