### ISSUE TITLE
Spike: Determine if an ARM template can replace the MLZ python user interface

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#260]
**Benefit/Result/Outcome**  
So that I have a simpler deployment using a visual interface from the Azure Portal

**Description**
ARM templates recently added the ability to run BASH commands. (https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template) Determine if this feature can be used to run a Terraform deployment.

We would like to have a "Deploy to Azure" button on the home page. Can this be done with the ARM template referenced above? Here's an example: (https://github.com/Azure/azure-quickstart-templates/tree/master/101-cloud-shell-vnet-storage)

**Acceptance Criteria**
- Can we run a Terraform deployment from an ARM template?
- Can the ARM template be used for a "Deploy to Azure" button in the default `README.md` document?
- If the answer to the above two questions is yes, create an issue in the MLZ backlog for implementing an ARM template.

**Comment by glennmusa** [comment]
I'm genuinely curious and am interested in invoking a container with arguments passed by input via ARM. Will cut a personal branch and link back to it.

**Comment by brooke-hamilton** [comment]
The related PR was moved to the [archive/frontend branch](https://github.com/Azure/missionlz/tree/archive/frontend). This issue is OBE due to Bicep.
