### ISSUE TITLE
As a user, I'd like to have some sort of .log file that occurs when I run automation in missionlz

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#27]
**Is your feature request related to a problem? Please describe.**
It's frustrating when things go wrong. It's even more frustrating if I don't have a way to know **what** went wrong. If something goes wrong (or right) with any of the automation in missionlz today the only way to know what had happened is if I access stdout.

**Describe the solution you'd like**
- I'd like for missionlz to have the capability to log what's happening in a file I can access on disk. 
- It should probably be gitignored for my own safety.

**Describe alternatives you've considered**
I guess I could expand my terminal history, or write out to App Insights in a RESTful way...but those seem complicated.

**Additional context**
Might be helpful for debugging issues as they're reported. Folks don't have enough information to answer what's wrong? Maybe a log file would help.

**Comment by brooke-hamilton** [comment]
Closing this as OBE given our approach to use Terraform as-is.
