### ISSUE TITLE
Check user permissions to re-use existing Service Principal

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#276]
**Benefit/Result/Outcome**  
I want to run `deploy.sh -s ${my_sub_id} --env-name ${glenn_cool_environment}` over and over again.

**Description**
Today, I can't do so because we require a unique service principal per deployment.

It'd be nice if MLZ checks to see if I have permissions to use an existing Service Principal and use that for the deployment credential. 

**Acceptance Criteria**
- Check for contextual user permissions to whatever identity will be used to deploy terraform configurations
- Given the user has adequate permissions, reuse the service principal instead of creating a new one

**Comment by brooke-hamilton** [comment]
This is now OBE given our approach to use Terraform as-is.
