### ISSUE TITLE
Port src/scripts to Python

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#277]
**Is your feature request related to a problem? Please describe.**
The more features we add to the BASH footprint, the more expensive it is to write new features and maintain source.

**Describe the solution you'd like**
Most AZ CLI extensions are [written in Python with the Knack framework](https://github.com/microsoft/knack) and seems like a natural place to start since a lot of the automation we do today is passing "objects" to interact with AZ CLI.

**Describe alternatives you've considered**
Porting to powershell core, porting to dotnet

**Additional context**
n/a

**Comment by brooke-hamilton** [comment]
Next step: spike to compare packaging a CLI in a single executable between Python and dot net.

**Comment by glennmusa** [comment]
Something worth considering, AZ CLI extensions are written in the knack framework that pushes a team into common CLI patterns and comes out-of-the-box with useful things like logging, eventing, user-configuration, etc: https://github.com/microsoft/knack/tree/dev/docs

**Comment by brooke-hamilton** [comment]
I have some additional thinking on this: I think we should define the problem being solved before we put this issue on the priority list. (That's a re-wording of the first bullet point in my previous comment.) I think we should wait on a spike to select a CLI framework until we are certain of what we will use it for. Maybe we already know, and if that's true let's put that info here. I'm currently unaware of what it would be. 😄

**Comment by brooke-hamilton** [comment]
Closing this because along with our work to implement Bicep we are removing most or all of the BASH scripting (but keeping Terraform.)
