### ISSUE TITLE
Export src/terraform/mlz output by default

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#278]
**Benefit/Result/Outcome**  
It would be helpful if the output from the main deployment was always available for reference.

**Description**
Today, the `--write-output` flag is an optional deployment setting. If I skipped this flag out of not-knowing it exists, when I go to deploy a Tier 3, the deployment will fail because the file could not be found.

The file is small and contains no secrets.

**Acceptance Criteria**
- Write the output by default
- Write the output with the environment name in the file name to keep consistency with how we generate .mlzconfig files and .tfvars files
- Write the output as .tfvars instead of json so that the tier3/main.tf maintains compatibility with user-supplied .tfvars files.
- Update the tier3/main.tf to remove the `.value` references
- Write to output silently -- today output is `tee`'d to a file, use redirect instead so that it doesn't appear in the stdout during apply

**Comment by glennmusa** [comment]
+ @sstjean

**Comment by brooke-hamilton** [comment]
@glennmusa do we still need this issue or is it OBE when we remove the scripting layer?

**Comment by brooke-hamilton** [comment]
Closing because the scripting layer for Terraform will be removed.
