### ISSUE TITLE
Spike: Idempotent deployments

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#279]
**Benefit/Result/Outcome**  
So that I can deploy `/src/terraform/mlz` over and over again with predictable results.

**Description**
Today, idempotency is achieved, but by Terraform destroying and recreating the environment when there are resources containing dynamic values not known until post-deployment with child resources that must also be re-created when those values change.

**Acceptance Criteria**
- Determine which resources need explicit values assigned such that they or their dependent resources are not recreated when I have not modified any other variables
- I can deploy MLZ over and over again without needing to destroy and recreate resources

**Comment by brooke-hamilton** [comment]
Closing this as won't fix because of other priorities.
