### ISSUE TITLE
PIP Availability Zones not available in all regions

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/missionlz#280]
**Description**
Public IP Address resources created by Terraform default to using `Zone-Redundant` for the `Availability-Zone` parameter. Availability zones are not available in all regions so when attempting to create a Public IP Address as part of a deployment to a region where Availability Zones are not supported, the deployment fails.

**Steps to Reproduce**
1. Attempt MLZ deployment to West US region in Commercial

**Expected behavior**
Deployment is successful

**Actual behavior**
Deployment fails with error stating that region does not support availability zones

**Screenshots**
![image](https://user-images.githubusercontent.com/16844071/124651099-84bee480-de68-11eb-8721-394ccb0c14aa.png)

**Additional context**
Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.):

**Comment by glennmusa** [comment]
@Phydeauxman pointed us to `availability_zone = No-Zone` for setting this regardless of cloud or region availability https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip#availability_zone

**Comment by glennmusa** [comment]
To add to the Firewall PIP, the Bastion PIP requires updating to `availability_zone = No-Zone` too
