### ISSUE TITLE
Non-Functional Switch: --config-sub-id

### ISSUE THREAD

**Issue by RKauf00** [Azure/missionlz#294]
Container based deployment using the --config-sub-id switch results in an Unexpected Argument error (-s works fine).

**Steps to Reproduce**
1. Attempt deployment using this code:

```bash
src/scripts/deploy.sh \
--config-sub-id <SubID> \
--hub-sub-id <SubID> \
--tier0-sub-id <SubID> \
--tier1-sub-id <SubID> \
--tier2-sub-id <SubID> \
--tier3-sub-id <SubID> \
--location usgovvirginia \
--tf-environment usgovernment
```

2. This code works fine:

```bash
src/scripts/deploy.sh \
-s <SubID> \
--hub-sub-id <SubID> \
--tier0-sub-id <SubID> \
--tier1-sub-id <SubID> \
--tier2-sub-id <SubID> \
--tier3-sub-id <SubID> \
--location usgovvirginia \
--tf-environment usgovernment
``` 

**Expected behavior**
Normal Deployment

**Actual behavior**
Deployment fails to start with Unexpected Argument error

**Screenshots**
![image](https://user-images.githubusercontent.com/26236368/125796683-ce46c686-53e7-4560-b30f-b18e274b6d1f.png)

**Additional context**
Operating System: Windows Subsystem for Linux (v2) Ubuntu 
Terraform Version: ?
Cloud (public, Azure Government, etc.): Azure Government

**Comment by glennmusa** [comment]
Thanks for opening an issue @RKauf00 👍

It looks like `--config-sub-id` is not an expected argument for deploy.sh. Looking at the `--help` for deploy.sh, the long-form name for the `-s` switch is `--subscription-id`:

```plaintext
            argument    description
   --subscription-id -s Subscription ID for MissionLZ resources
```

I do see how a name like `--config-sub-id` could be more clear, though. Will bring it up with the team to see if that's a more accurate name. 

In the meantime, like you mentioned, `-s` will get you setup, or using the currently implemented `--subscription-id` will too.

**Comment by RKauf00** [comment]
Good to know. I wasn't aware of the --subscription-id switch; I used the --config-sub-id switch based on the content in the generate_config_file.sh file

![image](https://user-images.githubusercontent.com/26236368/125802265-35a2c06b-6aa2-49bf-bade-58cac5358f48.png)
