### ISSUE TITLE
Non-Functional Switch: --tenant-id

### ISSUE THREAD

**Issue by RKauf00** [Azure/missionlz#295]
**Description**
Container based deployment using the --tenant-id switch results in an Unexpected Argument error

**Steps to Reproduce**
1. Attempt deployment using this code: 

```bash
src/scripts/deploy.sh \
--config-sub-id <SubID> \
--hub-sub-id <SubID> \
--tier0-sub-id <SubID> \
--tier1-sub-id <SubID> \
--tier2-sub-id <SubID> \
--tier3-sub-id <SubID> \
--location usgovvirginia \
--tf-environment usgovernment
```

**Expected behavior**
Normal Deployment

**Actual behavior**
Deployment fails to start with Unexpected Argument error

**Screenshots**
![image](https://user-images.githubusercontent.com/26236368/125798783-e23d0085-95dc-4e66-b7c3-ab61206feeef.png)

**Additional context**
Operating System: Windows Subsystem for Linux (v2) Ubuntu
Terraform Version: ?
Cloud (public, Azure Government, etc.): Azure Government

**Comment by glennmusa** [comment]
This looks similar to #294 in that the `--tenant-id` argument is for a different script to generate the configuration file, and is not an argument for `deploy.sh`, is that right?

**Comment by RKauf00** [comment]
Yes, please close both. I was referencing the wrong help file when I wrote my deployment cmd. Apologies for the confusion!

**Comment by glennmusa** [comment]
No worries! Happy to have the issue opened, it's what it's for! 👍
