### ISSUE TITLE
Provide a list of regions where MLZ successfully deploys

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#299]
**Benefit/Result/Outcome**  
So that I can know before deploying which regions will support MLZ.

**Description**
This work may be implemented as documentation only, or a combination of automation and documentation. Automation that produces the documentation would be preferable because the deployed services in each region are constantly changing, but an acceptable alternative is having the documentation of which regions successfully deploy MLZ and additional documentation on how to generate and validate that list (with as much automation support as possible.)

**Acceptance Criteria**
- A markdown document exists (or an update to an existing document) that shows which regions MLZ will successfully deploy in.
- Instructions on how to generate and validate the list, possibly with automation to support generating the list.

**Comment by glennmusa** [comment]
This may still be valuable and automated. Would be nice if something crawled the template and returned locations where all the provider types are available.

**Comment by brooke-hamilton** [comment]
> This may still be valuable and automated. Would be nice if something crawled the template and returned locations where all the provider types are available.

I added #603 to represent this.
