### ISSUE TITLE
NIST Network Compliance

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#312]
**Benefit/Result/Outcome**  
Review non-compliant policies of the default built in NIST 800-53 initiative and decide:

does the policy require work in Terraform to make compliant
or do we simply need to document additional work needed by customer to make compliant

**Description**
# Network

| Policy | Description |
| --- | --- |
| Azure DDoS Protection Standard should be enabled | DDoS protection standard should be enabled for all virtual networks with a subnet that is part of an application gateway with a public IP. |
| Subnets should be associated with a Network Security Group | Protect your subnet from potential threats by restricting access to it with a Network Security Group (NSG). NSGs contain a list of Access Control List (ACL) rules that allow or deny network traffic to your subnet. |

**Acceptance Criteria**
- Issues created to to either add documentation or compliance related feature change

**Comment by jamasten** [comment]
DDoS protection and the Bastion NSG are separate work items now. Firewall subnets don't require NSGs. All the other subnets within MLZ have an NSG.
