### ISSUE TITLE
Documentation on querying an MLZ deployment from other deployments

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#324]
**Benefit/Result/Outcome**  
Workload owners and IT Admins know how to query MLZ deployments to find the resource IDs and properties for specific MLZ assets. 

**Description**
IT Admins and workload owners will deploy additional resources into MLZ. Those deployments may be automated using a variety of tools. Integrating their deployment tools into the MLZ automation by enabling those tools to find specific MLZ assets, like resources and property values, will be an important aspect of using MLZ.

Examples of integration methods may be AZ CLI calls to find specific resources, queries from ARM/Bicep, and queries from Terraform.

**Acceptance Criteria**
- A markdown document exists that describes one or more ways to find MLZ resources using automated tools.
- Deployments in either Bicep or Terraform can retrieve needed deployment data
- Code examples are included.

**Comment by glennmusa** [comment]
Some of the first things that come to mind when onboarding "My New Spoke Virtual Network":

MyNewSpokeVirtualNetwork:
- a place to send my diagnostics (Log Analytics Workspace ID)
- a place to default route my traffic (Firewall Private IP Address)

Some of the things that come to mind after that, when onboarding a "My New Workload" into that new spoke virtual network:

MyNewWorkload:
- a place to securely store secrets like disk encryption keys (KeyVault)
- the Network Security Group my resources should join (Network Security Group)
- the Address Space I belong to so I can add resources to the network (Subnet Address Prefix)

Feel free to add more to this list and remind me of what I'm missing 👍

**Comment by shawngib** [comment]
This should be a set of quarriable values that allow the new mission owner to pull as needed these required values. It needs to take into account:
- MLZ deployed already and I may not own it so can't query it directly
- My mission/workload may have components that should be distributed into MLZ zones like operations or shared services
- My mission should work with existing deployments
    - for example - central logging

This should be script like 'deploy xyz in mlzNNNNNN'

**Comment by brooke-hamilton** [comment]
Closing as OBE now that we are using parameter files, which are documented in the examples section
