### ISSUE TITLE
Geo-redundant storage should be enabled for Storage Accounts

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#329]
**Benefit/Result/Outcome**  
*To be compliance clients should use geo-redundancy to create highly available applications. Currently MLZ uses storage accounts for diagnostic logging so this is primarily to document this control for future storage use. A separate issue will be created for central diagnostic logging. Note: This is a commercial policy but should be across clouds.*

**Description**
NIST SP 800-53 Rev. 4 CP-6 - The organization: a. Establishes an alternate storage site including necessary agreements to permit the storage and retrieval of information system backup information; and b. Ensures that the alternate storage site provides information security safeguards equivalent to that of the primary site.

**Acceptance Criteria**
- Document this as a control requirement and setting this via TF as well as out of band scripting. 
- Decide whether to set diagnostic storage as redundant.

**Comment by brooke-hamilton** [comment]
Closing - already implemented. Logs default to the `Standard_GRS` sku.
