### ISSUE TITLE
Evaluate STIGging VM images for compliance

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#332]
**Benefit/Result/Outcome**  
*Currently jumpboxes are deployed out of compliance with a number of the NIST control set but more importantly they are not STIG'd for DoD. There is currently market place items in all clouds for STIG'd linux and Windows VMs. These can be used on MLZ to reach compliance for DoD customers.*

**Description**
These market place items are market place templates so they require the underlying VM template (with custom code extensions) to be extended to TF/bicep  to work in MLZ

**Acceptance Criteria**
- Determine if STIGs are optional feature driven by a parameter, and which default?
- Yes/No the work effort to incorporate into MLZ a parametrized set of STIG'd jumpboxes. Parameter for settings and switch for -applyStig. 
- If yes to above questions, create the backlog items (GitHub Issues) to represent the work to be done.

**Comment by jamasten** [comment]
Customer responsibility.
