### ISSUE TITLE
Create a compliance matrix against SCCA FRD requirements 

### ISSUE THREAD

**Issue by ChristopherHolloway** [Azure/missionlz#337]
Need a clear outline of the compliance / governance blueprint mapping to the SCCA FRD and how IaaS/PaaS services are fulfilling those requirements natively while highlighting any additional customer responsibilities that are required

### BCAP
![image](https://user-images.githubusercontent.com/65698320/128589899-d092aec4-f3f0-4172-9e32-2ad2d2b235b5.png)

### ICAP
![image](https://user-images.githubusercontent.com/65698320/128589941-f655cca0-e604-4d70-89a2-358149288029.png)
![image](https://user-images.githubusercontent.com/65698320/128589959-a068cd80-7a05-4320-b5eb-ae90215c90d3.png)
![image](https://user-images.githubusercontent.com/65698320/128589970-b3b838be-416d-4ce2-b10b-72313d281795.png)

### VDSS
![image](https://user-images.githubusercontent.com/65698320/128589988-b913b02e-2727-4d43-8258-9d6e73af2b05.png)
![image](https://user-images.githubusercontent.com/65698320/128590001-ed710b4e-e4c9-41ab-96bb-fe9af5dc44b1.png)

### VDMS
![image](https://user-images.githubusercontent.com/65698320/128590026-15bcc7ee-09ec-48ed-9882-657871168b4a.png)
![image](https://user-images.githubusercontent.com/65698320/128590035-16a6e1c4-8d64-4134-a96b-1399c0ae684f.png)

### TCCM
![image](https://user-images.githubusercontent.com/65698320/128590048-2074bf88-1f9f-49ba-abec-d4a7b4c615f3.png)
![image](https://user-images.githubusercontent.com/65698320/128590059-958b76bf-6885-4e28-b1bb-478e6dc125c5.png)

**Comment by brooke-hamilton** [comment]
@ChristopherHolloway, thank you! 👍 Please take a look at the SCCA mapping document [here](https://github.com/Azure/missionlz/blob/main/src/docs/scca.md). I would love feedback on whether it meets the need you described, and if there are ways we can improve the document.

**Comment by brooke-hamilton** [comment]
I'm closing this item, but @ChristopherHolloway if you want to revisit the issue please let us know.
