### ISSUE TITLE
UI Config File Ingesters

### ISSUE THREAD

**Issue by Breanna-Stryker** [Azure/missionlz#34]
**Description**
In order to bridge the gap between the UI to terraform, scripts need to be written to ingest and output the required templates for various sections inside of a config file.

**Acceptance Criteria**
-  Script reads the config file and writes out the required files
- Script only writes out the sections specified during execution (I.E. if only making changes to Tier 3 and executing Tier 3 these are the only items processed)

**Comment by brooke-hamilton** [comment]
Closing as OBE
