### ISSUE TITLE
Run policheck on protected branches

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#346]
**Benefit/Result/Outcome**  

When I develop my new Bicep feature at `glennmusa/mynewfeature` and attempt to PR into `main` or `bicep` I expect an automated check that checks for acceptable language and terms.

**Description**

There's a policheck task provided by 1ES on internal Azure DevOps (ADO) Pipelines, we could run a pipeline referencing that task and pass the success/unsuccess as a GitHub Check on to PRs to the protected branches.

**Acceptance Criteria**

- On PR to protected branches, run this policheck ADO Pipeline and do not allow merge if the pipeline should fail.

**Comment by brooke-hamilton** [comment]
Closing - already done
