### ISSUE TITLE
Add Bicep VSCode extension to the dev container and to recommended extensions list

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#352]
**Benefit/Result/Outcome**  
So that all Bicep tools are installed by default

**Description**
The dev container and recommended extensions for this repository (applied when not using the dev container) need to have the Bicep VS Code extension added.

**Acceptance Criteria**
- Add the Bicep extension to the `extensions` section of the `.devcontainer/.devcontainer.json` configuration file.
- Add the Bicep extension to the `recommendations` section of the `.vscode/extensions.json` configuration file.

**Comment by glennmusa** [comment]
For tracking, this is currently implemented in the `/bicep` feature branch. Will associate this item with that eventual Pull Request to `/main`

**Comment by brooke-hamilton** [comment]
@glennmusa I think we don't need to track this since it's already done in the `/bicep` branch. Thank you! I'm going to close it but please re-open if you want to track it with the branch.

**Comment by glennmusa** [comment]
Oops! You're right! I mis-read this as `install bicep` not `install bicep extension` -- my mistake!

**Comment by brooke-hamilton** [comment]
My mistake - I reopened this because this work still needs to be done.

**Comment by brooke-hamilton** [comment]
Closed because this work is done. There was a syntax error in the link between this issue and the PR so the automation didn't close the issue.
