### ISSUE TITLE
Documentation for name resolution (DNS) within landing zones

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#353]
**Benefit/Result/Outcome**  
So that IT Administrators have guidance on implementing DNS as it applies to their specific scenario.

**Description**
We considered options for auto-deployment for at least one DNS scenario, however, we believe that the best name resolution solution will depend on how external traffic is configured and connected to the landing zone.  Therefore, we believe the best option for MLZ customers is to document the most likely scenarios.

**Acceptance Criteria**
- A markdown document exists (or a section within an existing document) that describes the most likely name resolution scenarios customers will encounter, and how to provide DNS within each scenario.
- Incorporate the scenario described in #392 so that customers can customize their deployments in that way

**Comment by lisamurphy-msft** [comment]
Potentially related to this question that was recently asked: #674

**Comment by lisamurphy-msft** [comment]
This can be resolved by https://github.com/Azure/missionlz/pull/746
Current implementation proposed in the following [example for IaaS DNS Forwarding](https://github.com/Azure/missionlz/tree/main/src/bicep/examples/iaas-dns-forwarders) gives customers a good overview of the challenges posed by integrating their MLZ deployment with DNS. 
Regarding the referenced question, (https://github.com/Azure/missionlz/issues/392) this has already been closed out.
