### ISSUE TITLE
Document (point to documentation) on how to run Terraform from Terraform CLI

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#354]
**Benefit/Result/Outcome**  

So that a user doesn't need to "know MLZ" to deploy the Terraform template in the repository, especially in a future where MLZ doesn't ship BASH scripts to do it on the user's behalf.

**Description**

In a future where we don't rely on the MLZ BASH scripts to deploy Terraform, but instead, defer that responsibility to the native Terraform tooling, we need to point the user to Terraform CLI docs on how Terraform `apply` and `destroy` work, how to find the appropriate value for the `tf_environment` variable, and how to use their own credential or a service principal credential. 

**Acceptance Criteria**
- Point to documentation on how to `terraform apply` and `terraform destroy`
- Point to documentation on which Terraform `tf_environment` value to use
- Point to documentation on how to run `terraform` as a Service Principal

**Comment by brooke-hamilton** [comment]
Related to #355
