### ISSUE TITLE
Use 'local' backend for Terraform modules by default

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#355]
**Benefit/Result/Outcome**  

A user could deploy Terraform from the repo without setting up dependencies.

In a future where MLZ doesn't provide BASH scripting to stand-up a Storage Account and Container for storing Terraform state, a `local` backend would instead allow the Terraform modules to be deployed independently. 

**Description**

https://www.terraform.io/docs/language/settings/backends/local.html

**Acceptance Criteria**
- Set the Terraform modules to `local` backend (and allowing the default path to be used) 
- Document (point to documentation) on how to use different backends 
- Document (point to documentation) on how to use the `azurerm` backend

**Comment by brooke-hamilton** [comment]
Related to #354
