### ISSUE TITLE
Remove `mlz_clientid` and `mlz_clientsecret` from Terraform provider declarations

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#356]
**Benefit/Result/Outcome**  

A user could deploy Terraform from the repo without setting up dependencies.

This allows MLZ to be beneficial in a future where MLZ doesn't provide BASH scripting to stand-up a Service Principal with Contributor RBAC permissions on behalf of the user.

**Description**

Instead, we could point to documentation on how to set the `client_id` and `client_secret` should the user need to deploy that way: https://www.terraform.io/docs/language/settings/backends/azurerm.html#client_id-1

**Acceptance Criteria**
- Remove the `mlz_clientid` from the Terraform modules
- Remove the `mlz_clientsecret` from the Terraform modules
- Update documentation to point users on how to set this themselves and when/why they would need to do this (when they do not own a Subscription, but instead are given a Subscription and a Service Principal that's authorized to update it)

**Comment by brooke-hamilton** [comment]
Related to #354, #355
