### ISSUE TITLE
Enable ssh-key access for mlzJumpboxLinuxVm

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#358]
**Is your feature request related to a problem? Please describe.**

If running MissionLZ under a subscription that has security options enforced, it is possible that this will not deploy successfully.
For instance, MissionLZ deployment will fail on the mlzJumpboxLinuxVM if there is enforcement of ssh key access to Linux VMs.

Additionally, upon failure there is retry logic that has the failed deployment attempt several iterations and expectedly continue to fail. There is little benefit to this. 

**Describe the solution you'd like**

Prefer that if the MissionLZ deployment fails, that it fails cleanly with more meaningful output to allow for a better user experience.

**Describe alternatives you've considered**

In this particular instance, disabling the security features that enforce ssh key access to Linux VM's was considered.

**Comment by brooke-hamilton** [comment]
The common approach with Bicep/ARM and the Azure Portal is to ask users to enter passwords for virtual machines. In command line deployments users are prompted to type passwords (stored as a secure string parameter) and on the Azure Portal users are asked to enter a password (also as a secure string parameter). There is an alternate approach in which a password is generated using shell script and stored in KeyVault, however there is some engineering work that has to go into incorporating the shell script into our Bicep/ARM deployments. We plan to take a look at doing this work in a future release (the project this backlog item is attached to.)

**Comment by glennmusa** [comment]
should be OBE https://github.com/Azure/missionlz/pull/406
