### ISSUE TITLE
Test and validate MLZ June release deployment in AGC using IB container

### ISSUE THREAD

**Issue by jjansen23** [Azure/missionlz#370]
**Benefit/Result/Outcome**  
To ensure that the Iron Bank container with the associated released version of mlz is deployable in agc.

**Description**
The Iron Bank container currently hosts the June release of MLZ. We need to ensure that the code, along with the correct az cli versions and terraform providers are able to execute in the agc

**Acceptance Criteria** 

- The MLZ code in the IB container deploys without the need to make any manual (code) changes. 
-  Any modification/ troubleshooting steps are documented for future implementation

**Comment by jjansen23** [comment]
Made the following changes in the IB container. 
1. Downgraded the az cli version from 2.26 to 2.22
2. Upgraded the azurerm provider from 2.55 to 2.67
3. Changed the location for the terraform plugins to a path that terraform uses as an internal mirror repo. The pasth is /usr/local/share/terraform/plugins

Uplifted the container for testing in agc

**Comment by glennmusa** [comment]
Closing for #386
