### ISSUE TITLE
Use of `uniqueString(deployment().name)` may cause issues, especially with storage account.

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#379]
**Description**
In using `uniqueId  = uniqueString(deployment().name)` to obtain an random like string ARM uses the deployment().name as a seed string to generate a 'semi' random string. The resulting use of the same deployment name will end up with the same random generated string. This can also cause issues with the storage account naming since it uses uniqueId which results in same name also.

**Steps to Reproduce**
1. Deploy `az deployment sub create --location usgovvirginia --name sg-mlztest --template-file ./mlz.bicep`
2. Notice the RG will be named with 'szxg4yhfjgtvq' as the unique string seeded from 'sg-mlztest'

**Expected behavior**
- Storage and RGs will continue to be named the same for each subsequent deployment.

**Actual behavior**
- To mirror current deployment models via Terraform this should be a totally unique string. Using `utcNow()` concatenated with deployment name will cause a more random like semi random unique ID since utcNow is exactly that, only now. Probably
- If 1 to 1 parity is not needed (which means no need for totally random unique ID) it should be documented, for those who  may believe this to be the same as the original TF repo.  Note: Keep in mind this may break storage account deployments.

**Screenshots**
![image](https://user-images.githubusercontent.com/8386143/131390588-3e1bccda-3640-4eaf-854f-11681832abb8.png)

**Comment by glennmusa** [comment]
This makes me think about idempotency and if that's a target of ours at all (it hasn't been so far). Should we generate a truly random seed in names, we'll have to consider that if we intend to deploy onto of a deployment:

> Be careful redeploying a Bicep file that relies on the utcNow function for a default value. When you redeploy and don't provide a value for the parameter, the function is reevaluated. If you want to update an existing resource rather than create a new one, pass in the parameter value from the earlier deployment.

from https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-date#remarks

**Comment by shawngib** [comment]
@glennmusa Agreed, work will be needed to develop a friendly to use random but repeatable/immutable deployment. In this case for step one it may be as simple as describing in doc what is being created and how it is using the deployment name to create a semi-unique name for resources. I think the larger concern is using the uniqueId value as the distinguishing value for storage account name. So if different users deploy with some name like 'testmlz' they will end up failing for same storage name which needs to be global Azure unique. "Your storage account name must be unique within Azure. No two storage accounts can have the same name."

**Comment by glennmusa** [comment]
The team agreed that we'll move forward using utcNow() for globally unique names in the intermediate, but that there's another backlog item for "make MLZ idempotent with some key (RG names maybe?)" and document how "idempotent" in air-quotes the deployment.

**Comment by brooke-hamilton** [comment]
This issue will be closed when #419 is closed.

**Comment by brooke-hamilton** [comment]
Closing because #419 is closed.
