### ISSUE TITLE
Test and validate MLZ July release for IB container

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#386]
**Benefit/Result/Outcome**  
To ensure that the Iron Bank container with the associated released version of mlz is deployable in agc.

**Description**
The Iron Bank container will be updated to host the July release of MLZ. We need to ensure that the code, along with the correct az cli versions and terraform providers are able to execute in the agc

**Acceptance Criteria** 

- The MLZ code in the IB container deploys without the need to make any manual (code) changes. 
-  Any modification/ troubleshooting steps are documented for future implementation

**Comment by jjansen23** [comment]
Successful deployment of IB across all clouds
