### ISSUE TITLE
Best Practice suggestion for routing VNet traffic within Tiers via AZ FW

### ISSUE THREAD

**Issue by DPirnia** [Azure/missionlz#392]
From Norm Ellis - I would like to suggest a “best practices” modification to the existing MLZ.  I’m not a terraform guru yet so not 100% sure which tf files these suggestions would be feathered into but:

1.	Update the applicable firewall tf to configure the Azure Firewall Policy -> DNS properties to “Enable DNS setting to be applied on the policy” & “Enable DNS Proxy”
 
2.	Update the applicable virtual-network tf to configure the DNS setting for each Tier Vnet to point to the public IP of the Azure Firewall.
 
![Norm1](https://user-images.githubusercontent.com/77843619/132052445-3107ac37-b878-4aef-9a2b-2cc63743b47a.png)
![Norm2](https://user-images.githubusercontent.com/77843619/132052447-a2436b58-9cd8-4655-81b3-36168ff22a6e.png)

By doing this we achieve two things:
1.	Centralize all DNS traffic through the Azure Firewall therefor providing a centralized point through which all DNS traffic can be logged and monitored.
2.	Automatically provides a DNS Resolver in Azure / aka a DNS proxy for which the customer can point an on-prem DNS conditional forwarder to. The on-prem conditional forwarder would point to the public IP of the Azure Firewall. This would allow a customers on-prem DNS to resolve resource records which reside in Azure Private DNS zones when private endpoints are used on resources like Storage accounts, Managed DBs, Key Vaults etc…

**Comment by glennmusa** [comment]
@glennmusa to investigate the DNS settings for Firewall PIP

**Comment by noellis-ms** [comment]
Update: By updating the applicable TF scripts for both the Azure Firewall and Vnets to enable the Az FW as a DNS Proxy, the following enhanced DNS features of the Az FW can be realized. See -> https://azure.microsoft.com/en-us/blog/new-enhanced-dns-features-in-azure-firewall-now-generally-available/

**Comment by brooke-hamilton** [comment]
Based on feedback from the team, this is a highly valuable scenario but it would not apply in all instances. The recommendation is to add documentation on using the DNS settings described in this issue.

**Comment by lisamurphy-msft** [comment]
The network design of MLZ is a hub and spoke model, where there are vnet peerings between the hub and the spokes in T0 through T3(n). Doing what is requested would change the network topology from hub and spoke to be a partial mesh ontology. In order to accomplish this, you can use some of the modules in this [directory](https://github.com/Azure/missionlz/tree/main/src/bicep/modules) and come up with a bicep related implementation  The simplest example on how to execute this is to use the [az cli](https://docs.microsoft.com/en-us/azure/virtual-network/create-peering-different-deployment-models) for example: 

```
az network vnet peering create \
--name vnetA-to-vnetB-sample \
--vnet-name vnetA \
--resource-group vnetAResourceGroup \
--remote-vnet /subscriptions/<subscription-id>/resourceGroups/<vnetBResourceGroup>/providers/
Microsoft.Network/virtualNetworks/vnetB \
--allow-vnet-access
```
