### ISSUE TITLE
BICEP: Autogenerated deployment name in NewWorkload template exceeds max length

### ISSUE THREAD

**Issue by timothysprock** [Azure/missionlz#393]
**Goal**: Deploy the NewWorkload template using the .json file.

**Issue**: Autogenerated deployment name in NewWorkload template exceed max length, so it fails to deploy the virtual peerings to the hub

**Template Input**: a new workload name that is less than 24 characters (aisSharedServices)

**Error Output**:
The provided deployment name 'aisSharedServicesbimsfltmjeeds-aisSharedServicesVirtualNetworkPeerings' has a length of '70' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details. (Code: InvalidDeployment)

See line:
https://github.com/Azure/missionlz/blob/276cdae118d650fcd98d9644b83f43b764342aa0/src/bicep/examples/newWorkload/newWorkload.json#L717

**Temp Solution/Workaround**:
I was able to successfully deploy the template by changing line 119 to:
`"name": "[format('{0}-{1}VirtualNetworkPeerings', parameters('workloadName'), parameters('workloadName'))]",`

Then the concat deployment name in this case is `aisSharedServices-aisSharedServicesVirtualNetworkPeerings`. However, with a 24 character limit on the workload name, one could still run into a "exceed max character" error

**Comment by glennmusa** [comment]
Thanks for opening an issue @timothysprock! Marking this as a bug and as something to fix.

Until the team is able to commit a fix, I might give the [take() function](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-array#take) a try for your max character error.

**Comment by brooke-hamilton** [comment]
@ExchMaster if the fix is something like using the take() function to limit the character length in the name, please also apply the same fix to `mlz.bicep` in which the spoke name is used to calculate a module name property. The spoke names can be overridden and could potentially cause the same issue as described in this bug.
