### ISSUE TITLE
Lint markdown on Pull Request to default branch

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#398]
**Benefit/Result/Outcome**  

So that the documentation is as high-quality as it can be.

**Description**

GitHub supplies the [SuperLinter action](https://github.com/github/super-linter) we can use to lint all *.md in the repository

**Acceptance Criteria**
- A `lint_markdown.yml` GitHub Action is invoked on all Pull Requests to the default branch
- Any unresolved warnings or errors prevents merging

**Comment by brooke-hamilton** [comment]
Related to #399
