### ISSUE TITLE
Update Sentinel examples with bicep modules

### ISSUE THREAD

**Issue by vidyambala** [Azure/missionlz#405]
**Benefit/Result/Outcome**  
*Write a single statement describing the value someone would receive when this issue is completed. Consider adding a persona label to define the role that will benefit, e.g. 'persona: IT admin'.*

**Description**
Replace Sentinel.tf with bicep module and update the readme document.

**Acceptance Criteria**
- 
-

**Comment by glennmusa** [comment]
I think this is closed by #359?
