### ISSUE TITLE
Enhance and extend current Log Analytics Workspace deployment

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#413]
**Benefit/Result/Outcome**  
As a customer installing and operating a mission landing zone I need to ensure monitoring is enabled in a meaningful and compliant manner. This requires:
 - specific retention policies on data (currently 30 days needs to be at least 365)
 - auditing the telemetry actions in the workspace itself against tampering with ability to lock workspace via parameter
 - ability to set workspace sku for cost
 - inclusion of minimum set of solutions, for example Security Insights (Sentinel), Security (ASC), VMM Insights and Azure Activity
 - data sources like VM logs to collect are centralized for MMA deployments pointed to this workspace
 
**Description**
As part of enabling Azure Monitoring Agent, which will be enabled via Policies as an extension added to each and every VM deployed, the VMM Insights OMS Solution will add value by coordinating a single location for centralizing telemetry collection

**Acceptance Criteria**
- Log Analytics Agent via policy - default true
- Dependency Agent via policy - default true
- Ensure Guest configuration via policy (already part of NIST) -default true
- Enable Azure Security Center - parameter for free/paid versions
- Additional parameters availability add to logAnalyticsWorkspace.bicep module
      * SKU
      * Retention Days defaulted to year but limited to in between 7-730 days - Document this setting change requirement for production installs needs to be greater than current default which is used for testing.
      * Solutions - array of new solutions
      * Data Sources - array of new data sources, like syslog and event log -document changes required for production
      * WS Lock = defaulted to false for testing
      * Diagnostic Settings on WS = defaulted to false 
      * Storage account to send WS Audit telemetry for outside of WS storage
- New workspace deployed as normal to Operations RG
       * Locked to prevent deleting if desired (delete lock type)
       * Diagnostic logging if desired to internal to LA as well as a storage
       * VMinsights solution, Security (ASC) solution, Security Insights (Sentinel) and Activity Log solution added to WS
       * Potentially a future item (spike) enabling additional solutions like Update Management and Change Tracking which wil be required for compliance best practices but this will require an automation account linked to WS in a different region (special region paired depending on WS region)

**Comment by sstjean** [comment]
@shawngib, @brooke-hamilton  - Is there any thought to splitting out the Log Analytics workspace to it's own RG and an additional RG for Security Operations (think playbooks, workbooks, alerts, etc)  This would make it easier for the SOC team to find and manager their resources.

**Comment by shawngib** [comment]
@sstjean Yes, to some degree. I am setting up compliance which includes security requirements in existing LA. Its probably layered in which a SOC would require/like a separate stream or resource group.
