### ISSUE TITLE
Update documentation with instructions to purge unused diagnostic logging settings

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#423]
**Benefit/Result/Outcome**  

So that if I incur the maximum diagnostic setting assignment count (5) for a subscription that makes a deployment "fail" I can remove settings.

**Description**

Today, if I deploy MLZ 5 times I'll incur the maximum diagnostic setting assignment count for my subscription(s). This is because the central logging to a Log Analytics Workspace setting is a subscription scoped resource and not a resource group scoped resource and deleting the MLZ deployed Resource Groups will clean up the Log Analytics Workspace, but not the diagnostic setting that sets the logging destination to that workspace.

As an idea, this little BASH snippet makes use of `xargs` to prompt the user for confirmed deletion:

```bash
az monitor diagnostic-settings subscription list --query "value[].name" --output tsv | xargs -otl az monitor diagnostic-settings subscription delete -n
```

**Acceptance Criteria**
- Provide documentation on how to clean up the diagnostic logging settings for a subscription after cleaning up a MLZ deployment

**Comment by shawngib** [comment]
@glennmusa and @brooke-hamilton Should this be in a larger subset of known issues? For example, cleaning up after testing and naming when not using the `--name` parameter of `az deployment create`?
