### ISSUE TITLE
Documentation on how to use Azure Portal to track Deployments

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#428]
**Benefit/Result/Outcome**  

Sitting around watching a dancing `Running` status isn't always the most fun. It's fun to watch the deployment!

Plus, it's helpful to redeploy just a single thing that failed if the rest of the deployment was successful.

**Description**

Document how to find your deployment in the Azure Portal and point to docs on how to use it.

**Acceptance Criteria**
- Updated docs for the bicep implementation

**Comment by brooke-hamilton** [comment]
Also link to existing docs on the azure portal.
