### ISSUE TITLE
Allow inclusion/exclusion of remote access host type via pass phrase parameter existence. 

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#433]
## Benefit/Result/Outcome

When deploying MLZ I can choose Linux and/or Windows as my jumpbox of choice. Currently it requires pass phrases for both.

## Description

When deploying I should be able to simply use the parameter setting for passphrase to understand my desire to deploy that particular OS version of a jumpbox. 

## Acceptance Criteria

-  Currently when deployment is run and Linux VM Admin password key is omitted an error happens. This should not be the case and the deployment should simply not deploy the Linux VM 
 
 Example:
 ``` 
az deployment sub create \
  --name "myRemoteAccessDeployment" \
  --location "eastus" \
  --template-file "src/bicep/mlz.bicep" \
  --parameters deployRemoteAccess="true" \
  --parameters windowsVmAdminPassword="$my_password"

**Comment by jamasten** [comment]
Not implementing.
