### ISSUE TITLE
Move the jumpboxes in the Terraform implementation into the existing Hub subnet

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#445]
## Benefit/Result/Outcome

Remove a subnet we don't need to create. Per @Phydeauxman this isn't necessary and can be removed. This also creates another route in the Firewall's route table that isn't necessary.

## Description

Today, the jumpboxes in the Terraform implementation create their own subnet:

https://github.com/Azure/missionlz/blob/main/src/terraform/mlz/main.tf#L384-L412

## Acceptance Criteria

-  Remove the jumpbox subnet
-  Update the jumpbox module to take in a dependency on the subnet created in the Hub

**Comment by glennmusa** [comment]
@Phydeauxman alternatively, which subnet should the jumpboxes belong to? The only other two subnets in the Hub that are created today are the Firewall Client and Firewall Management subnets:

https://github.com/Azure/missionlz/blob/7d6b27f7e32b7962d205d2dda33cf9ac1f0902fa/src/terraform/modules/hub/main.tf#L14-L26

**Comment by lisamurphy-msft** [comment]
Investigating and pulling this into the active workflow.

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
