### ISSUE TITLE
Generate an FAQ for MissionLZ

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#456]
**Is your feature request related to a problem? Please describe.**
As a systems integrator, I would like to have a centrally located FAQ document for customers to be able to ask questions and hopefully eventually create an automated, interactive bot

**Comment by brooke-hamilton** [comment]
Let's assemble this from community questions.

**Comment by brooke-hamilton** [comment]
This is a good idea, but for prioritization of resources for now I'd like to rely on the GitHub [discussions](https://github.com/Azure/missionlz/discussions) for questions and answers. If we redirect questions and answers there maybe we can generate enough content to move it into an FAQ document.
