### ISSUE TITLE
[Terraform] Check some allow-list before deploying Policy

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#458]
## Benefit/Result/Outcome

So that policy assignment doesn't fail if it's not supported in my cloud. 

(Originally a part of #454 but broken up so that it's an independent task and can be triaged separately.)

## Description

The policy assignment in a Terraform deployment may fail if some of the policies packaged in MLZ are not supported in a given cloud. Perhaps it's a good idea to create some allow-list of environments to compare before attempting to create policy assignments e.g.:

```terraform
locals {
  mlz_policy_environments = ["public", "usgovernment"] # terraform azurerm environments where the MLZ policies are supported
}

module "hub-policy-assignment" {
  count = var.create_policy_assignment && contains(local.mlz_policy_environments, lower(var.environment)) ? 1 : 0
}
```

## Acceptance Criteria

- The Terraform implementation of MLZ only deploys policies into the clouds we know support the policies packaged in MLZ
- Implement equivalent on Bicep

**Comment by brooke-hamilton** [comment]
Closing per @shawngib's recommendation.
