### ISSUE TITLE
Update CI/CD branch to use unique prefix in TF deployment

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#462]
## Benefit/Result/Outcome
Currently CI/CD has issues with naming conventions in TF deployment being the same for each deployment, there is also no tag to reflect this unique ID which would allow for scripting cleanup. Multiple issues arise when pipeline fails to be debugged separately from this issues. This is also designed to better align between the 2 type of deployments we have matching them to be similar. 

## Description

TF uses basic resource and resource group names with no longer uses a unique identifier for deployment like it does in Dicep.

## Acceptance Criteria

-  Resources and RGs have resourcePrefix variable that is unique per deployment used in the naming of each
-  This unique ID is added to tagging of resources to allow sorting and filtering for clean up and identification

**Comment by brooke-hamilton** [comment]
Closing - the project automation did not close this issue when the PR was merged
