### ISSUE TITLE
Create diagnostic settings module and incorporate into all modules

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#465]
**Is your feature request related to a problem? Please describe.**
Parity between TF and Bicep deployment results as well as central logging requirement for compliance. 

**Describe the solution you'd like**
Currently the Bicep deployment only sets diagnostic settings for virtual network metrics, activity logs and the central log analytics workspace itself. Terraform sets for firewall, publicIP, vnet and nsg. Terraform also sends to both LA workspace and storage accounts. 

**Describe alternatives you've considered**
This can be done by creating policies that enable diagnostic settings and then forcing remediation against each and can be done out of band. As policy via remediation it will incur latency in deployment as remediation applies changes but will also benefit by performing on any future resource deployments. Doing out of band risks being immediately out of compliance for basic requirement. 

**Additional context**
Diagnotic settings needs to be complete either on or off and shouldn't leave uncertain results.

**Comment by glennmusa** [comment]
Today's Terraform implementation configures these logs categories and the `All Metrics` metric for these resources:

Azure Firewall
- AzureFirewallApplicationRule
- AzureFirewallNetworkRule
- AzureFirewallDnsProxy
- AllMetrics

Public IP Address
- DDoSProtectionNotifications
- DDoSMitigationFlowLogs
- DDoSMitigationReports
- AllMetrics

Network Security Group
- NetworkSecurityGroupEvent
- NetworkSecurityGroupRuleCounter

Virtual Network
- AllMetrics
