### ISSUE TITLE
Update Bicep form with pre-deployment input validation

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#482]
## Description

Deploying using the marketplace UI template fails with this error:

```json
{
    "status": "Failed",
    "error": {
        "code": "InvalidResourceLocation",
        "message": "The specified location '[parameters('sharedServicesLocation')]' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."
    }
}
```

## Steps to Reproduce

Try to deploy from the Marketplace UI at `src/bicep/ui/` like so:

[![Deploy To Azure](https://raw.githubusercontent.com/Azure/missionlz/97d65ca653c7756c776ea56b4fa2e489847f6a46/docs/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fmissionlz%2Fbicep%2Fsrc%2Fbicep%2Fmlz.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fmissionlz%2Fmain%2Fsrc%2Fbicep%2Fui%2Fmlz-portal.json)

1.  Click the `Deploy to Azure` button
2.  Receive an error about shared services location

## Expected behavior

Deployment succeeds without modifying any input

## Actual behavior

Deployment fails on `InvalidResourceLocation`

## Screenshots

![image](https://user-images.githubusercontent.com/4622125/138742057-d36f0603-d304-45e9-a4d7-f910479b558b.png)

## Additional context

n/a

**Comment by brooke-hamilton** [comment]
Add a checkbox to the PR template that asks if the UI template has been updated when a parameter is added or changed.
