### ISSUE TITLE
Update the roleAssignment.bicep module principalType property so that warnings do not occur

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#486]
## Benefit/Result/Outcome

So that deployments do not present warnings.

## Description

Update the roleAssignment module's `principalType` to reflect the expected values:

Today's implementation:

https://github.com/Azure/missionlz/blob/6bdbf979621b74dcee701c824b3279c09e43b4c5/src/bicep/modules/roleAssignment.bicep#L4-L16

The expected values are one of `ForeignGroup, Group, ServicePrincipal, User, null` as reported by the Bicep warning below:

```plaintext
workspaces/missionlz/src/bicep/modules/roleAssignment.bicep(23,20) : Warning BCP036: The property "principalType" expected a value of type "'ForeignGroup' | 'Group' | 'ServicePrincipal' | 'User' | null" but the provided value is of type "'Application' | 'DirectoryObjectOrGroup' | 'DirectoryRoleTemplate' | 'Everyone' | 'ForeignGroup' | 'Group' | 'MSI' | 'ServicePrincipal' | 'Unknown' | 'User'".
```

## Acceptance Criteria

-  Role assignments still occur when necessary for policy, but without warnings at deployment time

**Comment by lisamurphy-msft** [comment]
Instead of updating the list of allowed types, to include a null value - I think it might make more sense to remove the @allowed stanza. Preliminary tests of this approach are returning successful - doing some additional testing and gathering peer feedback.
