### ISSUE TITLE
Nightly deployments of /main to AzureCloud and AzureUsGovernment

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#49]
**Description**

A nightly deployment that validates that the Bicep and Terraform templates work in the public and government clouds.

**Acceptance Criteria**
- A set of actions exists that will deploy the solution to the commercial and government clouds.
- Secrets are not stored in GitHub
- Functional tests are out of scope
- run `az deployment create` of Bicep on main (will be done in AzDevOps)
- run `terraform apply` of Terraform on main (will be done in AzDevOps)
- Notifications are available when the deployment breaks
- A pipeline success/fail badge on the root README

**Comment by glennmusa** [comment]
One idea is a GitHub Action with jobs for AzureCloud and AzureUsGovernment [GitHub Environments](https://docs.github.com/en/actions/reference/environments)

**Comment by glennmusa** [comment]
@vidyambala @brooke-hamilton updated the title and acceptance criteria with team decisions
