### ISSUE TITLE
Secure storage account networking

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#504]
## Benefit/Result/Outcome

Secure storage accounts in MLZ

## Description

- Storage account should use a private link connection
- Storage accounts should restrict network access using virtual network rules
- Access to storage accounts with firewall and virtual network configurations should be restricted

Update bicep to deploy SAs within a PL 
Update bicep to deploy SAs with restricted network access to vNet / subnets within the corresponding Tier (0, hub, 1, 2, 3)

## Acceptance Criteria

**Security findings resolved in ASC**
- Storage account should use a private link connection
- Storage accounts should restrict network access using virtual network rules
- Access to storage accounts with firewall and virtual network configurations should be restricted

**Comment by brooke-hamilton** [comment]
Need to check on V2 support across supported clouds.

**Comment by lisamurphy-msft** [comment]
should link this issue; we are presently using the default of TLS 1.0 on our storageAccount.bicep module: 
https://github.com/Azure/missionlz/issues/696

**Comment by lisamurphy-msft** [comment]
This is a slightly larger ask, will require pre-existing DNS Zones and/or DNS Zone groups. 
Additional questions regarding privateLink; storage accounts have several types of private links depending on resource type. 
For instance, there can be one for blob, queue, table etc.

**Comment by lisamurphy-msft** [comment]
I have updated storage accounts as V2 in bicep as part of #702 
It appears our bicep module is utilizing the storage account API that is newer then 2018-02-01 where this is being supported.
Also looks like the terraform implementation is already setting storage as StorageV2.

This doesn't yet solve the problem of the other acceptance criteria items however.
