### ISSUE TITLE
Add 'Azure Security Benchmark' policy initiative  deployment to policy options

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#509]
**Is your feature request related to a problem? Please describe.**
Currently only NIST, CMMC, and IL5 are options to assign as policy sets, these are not supported in all clouds and Azure Security Benchmark is. Adding this will allow those clouds to support a certain level of compliance auditing.

**Describe the solution you'd like**
Add /providers/Microsoft.Authorization/policySetDefinitions/1f3afdf9-d0c9-4c3d-847f-89da613e70a8 as an optional policy to add Azure Security Bencmark as an optional deployable policy set.

**Describe alternatives you've considered**
Not many options outside custom roll our own initiatives. 

**Additional context**

**Comment by shawngib** [comment]
The Azure Security Center policy is used ASC to be added to its default initiative.

Since this is already being set when `deployASC="true"` is used I am awaiting Byron's test for that.

**Comment by brooke-hamilton** [comment]
> The Azure Security Center policy is used ASC to be added to its default initiative.
> 
> Since this is already being set when `deployASC="true"` is used I am awaiting Byron's test for that.

@shawngib should we close this issue now that we are deploying Azure Security Benchmark with Azure Security Center/Defender?

**Comment by brooke-hamilton** [comment]
This work was completed with #560
