### ISSUE TITLE
Use "Configuration Sets" to make it easier to turn on/off resources in the Bicep deployment

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#514]
**Is your feature request related to a problem? Please describe.**

It'd be nice to be able to deploy Mission LZ by specifying just a "deploy these things only" configuration that MLZ could read to determine what resources to deploy in that environment.

Today, I have to know what boolean variables in MLZ to toggle to turn things on/off should I want/not-want those resources or if I found out they're not supported in my cloud.

**Describe the solution you'd like**

If I deploy to Cloud X, only deploy the things supported in Cloud X. 

If I deploy to Cloud Y, only deploy the things supported in Cloud Y.

If I want the "essentials" like just networking, only deploy the networking and nothing else.

If I want the "kitchen sink" like networking, and policy, and remote access, and security center, deploy all those things.

**Describe alternatives you've considered**

The "Configuration Set" pattern could prove valuable for creating some map that contains booleans to turn features on or off depending on what configuration the user wants to deploy.

See this example:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/patterns-configuration-set#example

```bicep
var environmentConfigurationMap = {
  AzureCloud: {
    centralLogging: true
    firewallPremium: true
    remoteAccess: true
    ...etc
  }
  SomeOtherCloud: {
    centralLogging: true
    firewallPremium: false
    remoteAccess: true
    ...etc
  }
  Essentials: {
    centralLogging: true
    firewallPremium: true
    remoteAccess: false
    ...etc
  }
  KitchenSink: {
    centralLogging: true
    firewallPremium: true
    remoteAccess: false
    ...etc
  } 
}
```

**Additional context**

Another scenario to consider when doing the spike: how could MLZ deployments be more modular? For example, deploy the network hub and tiers 0 and 1 only. Then deploy a tier 2 later. Or deploy only the network hub.

**Comment by glennmusa** [comment]
+@brooke-hamilton +@shawngib +@jjansen23 for their general interest in this area

**Comment by brooke-hamilton** [comment]
I added a comment under Additional Context. Moving this to next release, but I think this is an important piece of work.
