### ISSUE TITLE
Update the examples README.md to include not currently referenced examples

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#524]
## Benefit/Result/Outcome

The top level markdown document located at https://github.com/Azure/missionlz/tree/main/src/bicep/examples is missing a definition template for the inheritTags example. 

## Description

Update https://github.com/Azure/missionlz/tree/main/src/bicep/examples to include the other examples not currently referenced. 

## Acceptance Criteria

- The markdown document is updated to contain all examples.

**Comment by brooke-hamilton** [comment]
@ExchMaster this is the backlog item related to the examples documentation.
