### ISSUE TITLE
Error deploying to US Government cloud using Azure Cloud Shell

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#528]
## Description
Deploying with Azure Cloud Shell to the US Government cloud (environment = `usgovernment`) fails with an error. The error is caused by an issue in the Terraform Azure RM provider: https://github.com/hashicorp/terraform-provider-azurerm/issues/7787. This bug will be resolved when that issue is resolved and the fix is deployed to the Azure Cloud Shell on the US Government portal.

## Steps to Reproduce

1.  Launch azure cloud shell in Azure US Government (portal.azure.us)
2.  Follow the instructions at https://github.com/Azure/missionlz/tree/main/src/terraform#deploying-to-other-clouds to deploy to the US Government cloud.

## Expected behavior

Successful deployment

## Actual behavior
When running `terraform apply` the error below happens:

```TEXT
╷
│ Error: expected "access_policy.0.object_id" to be a valid UUID, got
│
│   with module.jumpbox[0].azurerm_key_vault.jumpbox-keyvault,
│   on ../modules/jumpbox/main.tf line 18, in resource "azurerm_key_vault" "jumpbox-keyvault":
│   18:     object_id = var.object_id
│
╵
```

## Workaround
Deployments to the US Government cloud succeeds using the development container.

## Additional context

Operating System: Azure Cloud Shell: portal.azure.us
Terraform Version: 
```TEXT
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.83.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```
Cloud (public, Azure Government, etc.): Azure Government (`usgovernment`)

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
