### ISSUE TITLE
Move parameters and variables to beginning of files in Bicep source

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#529]
## Benefit/Result/Outcome

To make source code a bit more readable on conform to some standards of practice the parameters and variables 

## Description

In the mlz.bicep main file the parameters and variables start at line 301. When bicep builds the json file for ARM it will host parameters and variable section at the top of the json.

## Acceptance Criteria

-  All bicep files run/build with parameters and variables moved to top of files.
-  All bicep files build to supported json not hitting json/ARM limitations:
-  Add parameters descriptors where prudent. @description and potentially @allowed in cases requiring more control

## Additional context: json/ARM Limitations:
4 MB files size (additional 4 MB for parameter file if used)
256 parameters
256 variables
800 resources (including copy count)
64 output values
24,576 characters in a template expression

**Comment by glennmusa** [comment]
Since they're moving, would this be a good opportunity to provide `@description`s for each parameter?

**Comment by shawngib** [comment]
Updated acceptance criteria to reflect the addition `@description` and `@allowed` where prudent.
