### ISSUE TITLE
Modify tags to allow adding custom tags without impacting default tags

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#530]
Tagging is a primary method for tracking owner, billing, operational sources and so on. Currently the `tags` parameter allows customers to set one or more tags via the command deployment but this replaces existing default tags which include prefix used and MLZ deployment method.  

**Describe the solution you'd like**
2 primary things to do: 
- add missing tags back to hub resource group module call in mlz.bicep.  
- Add a new variable representing default tags and then add the tags paramater object to it for passing to resources down the line.

Example:
 ```
var defaultTags = {
  'resourcePrefix': resourcePrefix
  'DeploymentType': 'MissionLandingZoneARM'
}
var tags = union(customTags, defaultTags )
```

Commands would add something like this:
```
tags='{"Owner":"Contoso","Cost Center":"2345-324"}'
customTags="$tags"
```

**Describe alternatives you've considered**
This would continue to include MLZ default tagging and force a bicep file change to delete, but still can be deleted in customers own fork.

**Comment by glennmusa** [comment]
I think this makes sense
