### ISSUE TITLE
Create examples of deployments via command line

### ISSUE THREAD

**Issue by shawngib** [Azure/missionlz#536]
## Benefit/Result/Outcome

We currently have a base exmaple/s set for deploying MLZ. It might benefit customers to see those examples in bash, PowerShell and using json via portal. These examples could use:

 for example creating parameter object in PowerShell:
![image](https://user-images.githubusercontent.com/8386143/142475823-cadf2eda-3d01-4377-a51f-3d48a1be3934.png)

creating parameters via file:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "<first-parameter-name>": {
      "value": "<first-value>"
    },
    "<second-parameter-name>": {
      "value": "<second-value>"
    }
  }
}
```

## Description

Ideally the examples will include a default parameter file they can customize, some default script commands they can copy and paste.

## Acceptance Criteria

-  Deployment examples to reflect using all available parameters:
    - PowerShell
             - with object
             - with file
             - command line directly
     - Bash command az cli: 
             - with object
             - with file
             - command line directly

**Comment by brooke-hamilton** [comment]
I'm temporarily removing this from a project backlog. Part of this work was done with #595 and I want to add scope for modifying the Bicep examples to be able to use any of these forms of setting parameters: PowerShell object, environment variables, parameters file, command line, and shared variable file pattern. That will mean removing the hard-coded references to a specific file path and providing each type of invocation with each example, but it will also allow adding the compiled ARM templates back into the source repo.

I will create a new backlog item that contains the scope above and close this one.

**Comment by brooke-hamilton** [comment]
I created #618 to represent this work.
