### ISSUE TITLE
Enable Azure Firewall Intrusion Detection policy by default

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#539]
## Benefit/Result/Outcome

To get closer to SCCA compliance, the Azure Firewall Premium SKU has Intrusion Detection that we can turn on by default.

## Description

Update the firewall policy resource to turn on Intrusion Detection defaulted to `Alert`:

https://github.com/Azure/missionlz/blob/9a3529b687889d63aea403dedfb0a798161242f1/src/bicep/modules/firewall.bicep#L24-L34

This can be enabled by defining a `firewallPolicyIntrusionDetection` property on the Azure Firewall Policy resource:

https://docs.microsoft.com/en-us/azure/templates/microsoft.network/firewallpolicies?tabs=bicep#firewallpolicyintrusiondetection

Here's a reference implementation (that has collections defined for `signatureOverrides` and `bypassTrafficSettings` that I presume we can leave empty for now):

https://github.com/Azure/azure-quickstart-templates/blob/c4e7342e0046ea4fe120749514b54f37daf05dce/quickstarts/microsoft.network/azurefirewall-premium/azuredeploy.json#L333-L361

## Acceptance Criteria

- Azure Firewall Intrusion Detection is turned on by default and set to `Alert`
- Need more detail before committing to this: what are the correct settings for [FirewallPolicyIntrusionDetectionConfiguration](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/firewallpolicies?tabs=bicep#firewallpolicyintrusiondetectionconfiguration)

**Comment by glennmusa** [comment]
@shawngib has a working implementation to just turn it on, but we need more detail before committing to this:

For MLZ, what are the correct settings for [FirewallPolicyIntrusionDetectionConfiguration](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/firewallpolicies?tabs=bicep#firewallpolicyintrusiondetectionconfiguration)?

**Comment by shawngib** [comment]
Just wanted to add that there is also currently a bug in the FFX portal preventing users from manually doing this in the portal. So currently only option is set at deployment or script afterwards.
