### ISSUE TITLE
Validate the length of the resourcePrefix parameter

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#548]
## Benefit/Result/Outcome

User input from the `resourcePrefix` parameter in `mlz.bicep` is used to calculate some of the resource names. The input has insufficient validation to prevent resource names from exceeding the maximum resource name length, which can result in deployment errors that do not make it obvious to the user that the deployment failed because the input was too long.

## Description

Add validation to limit the `resourcePrefix` parameter to a maximum length that will not cause errors in resource name concatenation that uses the `resourcePrefix` name as input.

The suggested approach in figuring out the max length of  `resourcePrefix` is to examine the code for all uses of the parameter, and find the resource name that has the lowest limit. Keep in mind that some of the uses are downstream, e.g. `resourcePrefix` is used to calculate `hubResourceGroupName` which is used to calculate `identityResourceGroupName`. 

Another possible approach is to use truncation to prevent resources from exceeding their name lengths. However, that approach is not recommended because for each resource type a decision would have to be made about which part of the resource name to truncate. If too much of the static identifiers in a name are truncated then the names may not be unique, but if too much of the user-supplied parameter is truncated then that may also result in resources not having unique names.

This backlog item is derived from #531. 

## Acceptance Criteria

-  The `resourcePrefix` parameter has a maximum length validation that prevents any derived resource names from failing deployment due to exceeding resource type length constraints.

**Comment by glennmusa** [comment]
From our previous discussions, I think the "right" decision might emerge when names are calculated e.g. `rg-resourcePreifx-uniqueishIdentifier-eastus2-prod` and agree this could be removed.

**Comment by brooke-hamilton** [comment]
Closing as OBE - I was not able to trigger any errors by deploying with long deployment names or `resourcePrefix` parameter values.
