### ISSUE TITLE
Create naming conventions for resources

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#556]
## Benefit/Result/Outcome

So that deployed resources adopt generally accepted naming practices while providing a single place in source to modify the naming convention.

## Description

We can use Bicep's string interpolation to create naming conventions and use Bicep's `replace()` function to do token replacement.

For example, given a `resourcePrefix=foo` and `resourceSuffix=bar`, here's how a naming convention could be defined, with reserved terms like `<x>_token` used for token replacement.

1. First, we define the naming convention:

    - https://github.com/Azure/missionlz/blob/1429d94f1824e4d3581b955479c1f5d221494578/src/bicep/mlz.bicep#L17

2. Then, we could do token replacement for resource type abbreviations. For example, here on L27 generating a resource group naming convention like `foo-rg-mlz_token-bar`:

    - https://github.com/Azure/missionlz/blob/1429d94f1824e4d3581b955479c1f5d221494578/src/bicep/mlz.bicep#L19-L31

3. Finally, using another `replace()` call to replace the next token, `mlz_token`. For example, here on L44 generating a hub resource group name like: `foo-rg-hub-bar`:

    - https://github.com/Azure/missionlz/blob/1429d94f1824e4d3581b955479c1f5d221494578/src/bicep/mlz.bicep#L42-L97

## Acceptance Criteria

- Adopt a [naming convention](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming) for the resources named at mlz.bicep
- Use the [recommended abbreviations](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) where possible 
- Provide an obvious mechanism to override naming conventions
- Document how to override naming conventions
- All resource names are in lower case
- An additional optional parameter is defined as resourcePostfix which allows deploying into the same subscriptions but different regions. It will default to "mlz"
- Include resourcePostfix in automatic tags.
- The seed for unique() calculations is the concatenation of resourcePrefix and resourcePostfix
- User input generates a unique name using the Bicep uniqueString function.
- The resulting unique string is passed to a module that creates a storage account using the unique string as part of the storage account name.
- The storage account can be deployed multiple times without destroying and recreating, preserving idempotency.

**Comment by glennmusa** [comment]
Created this to address some of the acceptance criteria in #549

**Comment by glennmusa** [comment]
Started this work at [glenn/namingConventions](https://github.com/Azure/missionlz/tree/glenn/namingConventions)

**Comment by brooke-hamilton** [comment]
@glennmusa I added these acceptance criteria from #503 and #549. I will close those backlog items.

- All resource names are in lower case
- An additional optional parameter is defined as resourcePostfix which allows deploying into the same subscriptions but different regions. It will default to "mlz"
- Include resourcePostfix in automatic tags.
- The seed for unique() calculations is the concatenation of resourcePrefix and resourcePostfix
- User input generates a unique name using the Bicep uniqueString function.
- The resulting unique string is passed to a module that creates a storage account using the unique string as part of the storage account name.
- The storage account can be deployed multiple times without destroying and recreating, preserving idempotency.
