### ISSUE TITLE
mlz-pr-* PR checks do not run for forked branches

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#592]
## Description

PR checks prevent approving any PR from a fork.

When PRs are created from forks, the automated PR checks that begin with `mlz-pr-*` do not run. They show "Expected — Waiting for status to be reported" and they never run. 

Running `/azp run` does not trigger the pipelines. 

There is no break-glass method of approving the PR. (The "use your privileges to approve" button is not available.)

1. Fork the repo into a different org or personal GitHub account
2. Submit a PR from the fork. 

## Expected behavior

All checks run.

## Actual behavior

PR checks that begin with `mlz-pr-*` do not run. See #591

## Screenshots

![image](https://user-images.githubusercontent.com/45323234/147109364-77bdfef6-e69e-4dd7-bdac-b2175de24320.png)

**Comment by brooke-hamilton** [comment]
@vidyambala, should these PR checks run as GH actions instead of AZ Pipelines? The PoliCheck and CredScan tools require AZ Pipelines, but I think the `mlz-pr-*` checks do not.

**Comment by vidyambala** [comment]
@brooke-hamilton - Supposed to run same as Policheck and CredScan. Will check the settings of those PR pipelines.

**Comment by glennmusa** [comment]
fixed as part of #591
