### ISSUE TITLE
Azure Automation Bicep template

### ISSUE THREAD

**Issue by kzoltani** [Azure/missionlz#593]
Thank you for the MLZ, its a great example to learn from. It would be beneficial if a Azure Automation BICEP template was included as its a pivotal service which is leveraged for account management and updates. Also its integration with Log Analytics Workspaces would be wonderful. Thank you

**Comment by brooke-hamilton** [comment]
@kzoltani thank you for the feedback! Are you asking for a new template in the `src/bicep/examples` folder? And this new template would configure Azure Automation and forward the automation logs to Log Analytics?

**Comment by kzoltani** [comment]
@brooke-hamilton Yes, that would be wonderful and useful

**Comment by glennmusa** [comment]
foe reference https://github.com/Azure/bicep/tree/main/docs/examples/301/automation-account-import-runbooks-and-modules

**Comment by brooke-hamilton** [comment]
I created backlog item #604 to represent this work. @kzoltani please take a look at it and let me know what you think--especially the acceptance criteria. Thank you for the feedback that led to creating this backlog item! 👍

**Comment by brooke-hamilton** [comment]
@kzoltani this is done as part of #604 and it is merged to the main branch. You can see it at `src/bicep/examples/automationAccount`. Thank you for the feedback/suggestion that resulted in this being done! ✨
