### ISSUE TITLE
Automated discovery of regions where MLZ can deploy

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#603]
## Benefit/Result/Outcome

So that for any given cloud, e.g. `AzureCloud`, `AzureUSGovernment`, etc., an IT Administrator can know which regions support deploying Mission Landing Zone.

## Description

MLZ depends on specific resource providers that are defined in the Bicep and Terraform templates. This spike is to determine the feasibility of providing a utility (probably a PowerShell or BASH script) that can be run on a specific cloud to compare the resource providers in the compiled ARM template with the resource providers available in each region, and show the intersection. Potentially also show all the regions and which resource providers are not available in each region. 

## Acceptance Criteria

-  A single command, e.g. script, can be run that will inform the user about which regions in a specific cloud will support MLZ.
- The command output shows a list of all regions and indicates if MLZ can be deployed in the region.
- For regions where MLZ cannot be deployed, the command output shows which resource providers do not exist.
- The command output shows both Terraform and Bicep/ARM, or separate commands exist: one for Bicep/ARM and one for Terraform.

**Comment by brooke-hamilton** [comment]
To Do: Need to refactor this into multiple backlog items. This work is important but is a lower priority than other things right now. However, please comment here if you need this and we can re-evaluate.

**Comment by jamasten** [comment]
This can be handled with the UI definition.
