### ISSUE TITLE
Add diagnostic settings to T3

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#605]
## Benefit/Result/Outcome

So that IT Administrators can deploy multiple instances of Tier 3 (new workloads) and have consistent diagnostic settings that forward logs to the operations tier.

## Description

We want to demonstrate how to apply diagnostic settings to all Tier 3 subscriptions and resources. Ideally this would be done via policy assignment in a management group. However, MLZ does not assume that customers have the rights to create management groups, so we will demonstrate how to create and assign the policies, assign them at the T3 subscription level, and provide guidance on how the same policies can be set up in a management group.

## Acceptance Criteria

- NSG log settings for Tier 3 are enabled the same as for other network spokes. 
- Subscription-level activity logging is enabled the same as it is for other subscriptions, i.e., if T3 is deployed to it's own subscription then enable central activity logging. See `centralLogging.bicep`.
- Documentation exists with the T3 template that explains how these log settings are configured and describes why it would be helpful to set them via policy or audit if a policy does not exist.
- The log settings are implemented in both Bicep and Terraform

**Comment by shawngib** [comment]
I don't think we have a specific policy for NSG (this may have changed) but I believe the other policies audit it. Maybe this 'A policy to create NSG log settings is part of the T3 Bicep and Terraform templates.' is related to simply enabling logging done in NSG module?

**Comment by brooke-hamilton** [comment]
> @brooke-hamilton I don't think we have a specific policy for NSG (this may have changed) but I believe the other policies audit it. Maybe this 'A policy to create NSG log settings is part of the T3 Bicep and Terraform templates.' is related to simply enabling logging done in NSG module?

I updated the acceptance criteria:
- ~~A policy to create NSG log settings is part of the T3 Bicep and Terraform templates.~~
- NSG log settings for Tier 3 are enabled the same as for other network spokes. 
- ~~A policy to create subscription-level activity logging (similar to our centralLogging.bicep configuration) is part of T3 Bicep and Terraform templates.~~
- Subscription-level activity logging is enabled the same as it is for other subscriptions, i.e., if T3 is deployed to it's own subscription then enable activity logging. See `centralLogging.bicep`.
- ~~The policies assignments are deployed to the resource group for T3.~~
- Documentation exists with the T3 template that explains how these log settings are configured and describes why it would be helpful to set them via policy or audit if a policy does not exist.
