### ISSUE TITLE
Document the need for and side effects of using `Microsoft.Security/policies` resource provider

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#606]
## Benefit/Result/Outcome

So that a person who sees the warnings emitted by the code has confidence in the quality of MLZ.

## Description

The `Microsoft.Security/policies@2015-06-01-sdpreview` resource provider is used in our Bicep code to deploy the policy assignment associated with the advanced version of Azure Security Center/Defender. The provider is not documented and generates a Bicep warning, which causes users to wonder why the provider is being used.

## Acceptance Criteria

-  Suppress the warning emitted by the code using the `#disable-next-line <rule or warning>` Bicep syntax.
- Add a comment to the `Microsoft.Security/policies@2015-06-01-sdpreview` module explaining why the resource provider is being used.

**Comment by glennmusa** [comment]
as of Bicep 0.4.1124 the `#disable-next-line <rule or warning>` syntax allows for supressing individual warnings:

> ![DisableNextLineDiagnostics](https://user-images.githubusercontent.com/30270536/140797130-7f268cdd-e056-4aba-b4a2-ec5240237a67.gif) 

https://github.com/Azure/bicep/releases/tag/v0.4.1124

**Comment by brooke-hamilton** [comment]
> as of Bicep 0.4.1124 the `#disable-next-line <rule or warning>` syntax allows for supressing individual warnings:
>  
> https://github.com/Azure/bicep/releases/tag/v0.4.1124

Thanks! I updated the acceptance criteria to specify the `#disable-next-line <rule or warning>` syntax.

**Comment by brooke-hamilton** [comment]
Closing: #485 makes this backlog item OBE
