### ISSUE TITLE
Terraform destroy fails on firewall delete "Error: deleting Azure Firewall Firewall"

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#609]
## Description

Running `terraform destroy` in `AzureCloud` from our pipeline agent fails with a 415 `"The content media type '<null>' is not supported. Only 'application/json' is supported"`:

```plaintext
Error: deleting Azure Firewall Firewall: (Azure Firewall Name "firewall" / Resource Group "{resource group name}") : network.AzureFirewallsClient#Delete: Failure sending request: StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '<null>' is not supported. Only 'application/json' is supported."
```

## Steps to Reproduce

1.  Run the nightly Terraform AzureCloud pipeline

## Expected behavior

The firewall is successfully deleted and the pipeline finishes the `terraform destroy` task.

## Actual behavior

The firewall is not deleted, it and its parent resource group must be manually deleted, and the pipeline fails.

## Additional context

The `azurerm` team also encounters this error: https://github.com/hashicorp/terraform-provider-azurerm/pull/14907#pullrequestreview-850009879

For academic purposes, it reads like this is the method bubbling up the error: https://github.com/hashicorp/terraform-provider-azurerm/blob/67e95001cc7ed859f2bd589c426f4e5bc056d237/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-05-01/network/azurefirewalls.go#L145-L149

Operating System: ubuntu
Terraform Version: 1.13 and azurerm 2.90.0
Cloud (public, Azure Government, etc.): AzureCloud

**Comment by glennmusa** [comment]
The firewall is now able to be destroyed successfully.

**Comment by glennmusa** [comment]
This error has returned.

**Comment by brooke-hamilton** [comment]
Should we change the cleanup to delete the resource groups and subscription-level diagnostic settings?

**Comment by glennmusa** [comment]
^ I think it's a good idea as long as the "nightly status" still shows failure if the Terraform commands are unable to round-trip creation and deletion. Could put it in another always run job in the existing pipeline.

**Comment by brooke-hamilton** [comment]
I will convert this to a backlog item that will implement resource group deletes.

**Comment by brooke-hamilton** [comment]
Created #640 to replace this bug.
