### ISSUE TITLE
Portal UI does not capture passwords for Remote Access with "Failed to create element of type: 'Microsoft.Compute.CredentialsCombo' named 'linuxVmSection,linuxVmAdminPasswordOrKey'"

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#615]
## Description

The credentials combobox for collecting passwords is throwing an error in the Portal UI:

![image](https://user-images.githubusercontent.com/4622125/150204565-f0aff644-0bba-45ba-bb5c-be1f104a7b0b.png)

Navigating away from the pane and returning to it clears the error, but the credentials comboboxes do not render:

![image](https://user-images.githubusercontent.com/4622125/150204941-acb4eba8-d353-49ee-bd86-e09d8510137e.png)

## Steps to Reproduce

1.  Click the Deploy to Azure button on the root README
2.  Add the required information until you get to the "Remote Access" pane

## Expected behavior

I can create jumpboxes and specify their passwords from the Remote Access pane in the Portal deployment

## Actual behavior

I cannot specify passwords for the jumpboxes.

## Additional context

Cloud (public, Azure Government, etc.): AzureCloud, AzureUsGovernment

**Comment by shawngib** [comment]
@glennmusa  and @brooke-hamilton Not sure this helps or not but here is a snippet I am borrowing for ASH UI that uses combo box selection to then offer either the SSH or Password box.

``` 
                    {
                        "name": "adminCredentials",
                        "type": "Microsoft.Compute.CredentialsCombo",
                        "label": {
                            "authenticationType": "Authentication type",
                            "password": "Password",
                            "confirmPassword": "Confirm password",
                            "sshPublicKey": "SSH public key"
                        },
                        "toolTip": {
                            "authenticationType": "Authentication type (password or ssh public key) to connect to the virtual machine",
                            "password": "Admin password for the virtual machine",
                            "sshPublicKey": "Admin ssh public key for the virtual machine"
                        },
                        "constraints": {
                            "required": true,
                            "customPasswordRegex": "^(?=.*[A-Z])(?=.*[.!@#$%^&*()-_=+])(?=.*[0-9])(?=.*[a-z]).{12,40}$",
                            "customValidationMessage": "Password must be at least 12 characters long, and contain upper case, lower case, number and symbol"
                        },
                        "options": {
                            "hideConfirmation": false,
                            "hidePassword": false
                        },
                        "osPlatform": "Linux",
                        "visible": true
                    }
