### ISSUE TITLE
Deploy a private marketplace offering with the existing Declarative Form UI

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#627]
## Benefit/Result/Outcome

So that the existing Declarative Form Portal UI can be used in private marketplace offerings.

## Description

Today, using the current mlz.portal.json that launches the ["Deploy to Azure" experience in the root README](https://github.com/azure/missionlz#deploy-from-the-azure-portal) in a private marketplace offering results in an exception in the Portal that bubbles up as: `Cannot set properties of undefined (setting 'injectedBasics')`.

This spike is to determine if there is something that can be done to the existing Declarative Form UI to provide a view that successfully deploys.

## Acceptance Criteria

-  the spike is time-boxed to one day
-  document what was attempted and what to do next

**Comment by glennmusa** [comment]
#625 illustrates a course of action if this cannot be achieved

**Comment by glennmusa** [comment]
One thing the team mentioned is adding the two `basics` members (L7 and L9 below) found in the createUiDefinition schema and seeing if that could still work in both the `Deploy to Azure` public scenario and private marketplace scenario:

https://github.com/Azure/missionlz/blob/92acb78330c1c58227175763f87c589d38986d4a/src/bicep/form/mlz.portal.json#L1-L12

**Comment by brooke-hamilton** [comment]
> NOTE: Testing requires putting the form back into preview.

**Comment by glennmusa** [comment]
This error:

```plaintext
Cannot set properties of undefined (setting 'injectedBasics')
```

is circumventable by removing the `isWizard` property from the `view.properties` object:

https://github.com/Azure/missionlz/blob/92acb78330c1c58227175763f87c589d38986d4a/src/bicep/form/mlz.portal.json#L15

However, was still unable to get a Declarative Form to successfully deploy with the Partner Center's publication mechanism. Will continue discussions in internal channels and update this Issue as relevant.

**Comment by glennmusa** [comment]
We've picked this discussion up with the relevant teams. Will continue to update this thread as we learn more.

**Comment by glennmusa** [comment]
Removing from in-progress. The team needs to discuss marketplace as a publishing avenue.

**Comment by brooke-hamilton** [comment]
Moving this to draft until we get support in the AGCs

**Comment by jamasten** [comment]
We have no plan to offer MLZ in the marketplace. Instead, we plan to offer the JSON files to create a template spec for simplified deployments.
