### ISSUE TITLE
Update the name for Azure Security Center to Microsoft Defender for Cloud

### ISSUE THREAD

**Issue by DPirnia** [Azure/missionlz#628]
Field folks asked if we are planning to update the https://github.com/Azure/missionlz/blob/main/docs/scca.md and other instances that reference Azure Security Center with the new name - Microsoft Defender for Cloud.

**Comment by DPirnia** [comment]
The name for Azure Security Center and Azure Defender are now called Microsoft Defender for Cloud. https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/a-new-name-for-multi-cloud-security-microsoft-defender-for-cloud/ba-p/2943020 

2 of our field CSAs who are working with customers to deploy MLZ have stated that our site reflects Azure Security Center, which is now rolled into Microsoft Defender for Cloud (along with Azure defender). 

Can we do a search and replace to update the language wherever Azure Defender or Azure Security Center appear and change them to reflect the current name: Microsoft Defender for Cloud. 

The business value of this is that using current language where customers and external customers will consume data about MLZ and its integrated services will help to drive clarity.

**Comment by brooke-hamilton** [comment]
I created backlog item #630 to represent this work. Closing this.
