### ISSUE TITLE
Automate and define work tracking for failed nightly builds

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#629]
**Is your feature request related to a problem? Please describe.**

Typically, when builds fail in our nightly testing, it is addressed by a small subset of people on our team as an ad-hoc basis. 
It is hard for this to be a force multiplier because it is untracked and undocumented work. 

**Describe the solution you'd like**

When a testing build fails, a ticket is auto-generated for the investigation and we define a process to deal with these failures programmatically.

**Comment by brooke-hamilton** [comment]
I will draft a paragraph in the CONTRIBUTING.md guide to describe how to handle these. The general idea is that as a team we are responsible for build breaks, so when it happens someone will volunteer to handle it. Handling can include creating a bug in the repo, or sometimes it will be as simple as re-queuing the build.
