### ISSUE TITLE
Add the bicep binary to the Iron Bank container

### ISSUE THREAD

**Issue by jjansen23** [Azure/missionlz#639]
## Benefit/Result/Outcome

When working in clouds that do not have internet connection, it is sometimes necessary to make code changes to the Bicep modules. Having a full installation of Bicep available will allow for the generation of .json files
## Description

Select the latest version of Bicep and add this to the container that is hosted in the Iron Bank repo.

## Acceptance Criteria

-  The Iron Bank container has the Bicep binaries
-  The Bicep binaries can be invoked and used, from the container, in a disconnected from the internet, environment

**Comment by glennmusa** [comment]
```dockerfile
# Install Bicep
RUN \
    # Fetch the latest Bicep CLI binary
    curl -Lo bicep https://github.com/Azure/bicep/releases/${BICEP_VERSION}/download/bicep-linux-x64 \
    # Mark it as executable
    && chmod +x ./bicep \
    # Add bicep to your PATH (requires admin)
    && mv ./bicep /usr/local/bin/bicep \
    # Verify you can now access the 'bicep' command
    && bicep --help
```

https://github.com/Azure/vscode-remote-try-bicep/blob/78d5170232c4a3db9f5a410346e57e0692162fdc/.devcontainer/Dockerfile#L22-L31

**Comment by kyle-hoyer** [comment]
Iron Bank container no longer supported or updated for deployment.
