### ISSUE TITLE
Generate the Defender pricing bundle array from a resource provider

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#649]
## Benefit/Result/Outcome

So that supported ASC/Defender bundles are deployed with MLZ without having to maintain a static list in sync with each cloud.

## Description

In `securityCenter.bicep` we have a line of code that creates an array of pricing bundle names:

```Bicep
var bundle = (environment().name != 'AzureUSGovernment' ? [  
  'KeyVaults'
  'SqlServers'
  'VirtualMachines'
  'StorageAccounts'
  'ContainerRegistry'
  'KubernetesService'
  'SqlServerVirtualMachines'
  'AppServices'
  'Dns'
  'Arm'
  ] : [
  'SqlServers'
  'VirtualMachines'
  'StorageAccounts'
  'ContainerRegistry'
  'KubernetesService'
  'Dns'
  'Arm'
])
```

The list of available bundles is different in each cloud, so rather than add a new list for every supported cloud, investigate whether we can use a resource provider from Bicep to retrieve the list.

**Work on this spike is limited to 4 hours**

## Possible Outcomes

The spike will result in one or more of the following outcomes:

- `securityCenter.bicep` is updated to retrieve the pricing bundle array from a resource provider.

**Comment by brooke-hamilton** [comment]
A valid outcome is to apply no bundles for clouds other than commercial and US Government.

**Comment by glennmusa** [comment]
I don't see a downside to a third branch of the conditional check that defaults to an empty array. Is there one?

**Comment by brooke-hamilton** [comment]
> I don't see a downside to a third branch of the conditional check that defaults to an empty array. Is there one?

Ideally we would query the list from the resource provider and enable all of them, but I agree that an empty array also works plus documentation in the deployment guide specifying that users will have to enable the bundles on their own.

**Comment by lisamurphy-msft** [comment]
This might need to be a feature request to the service owner of the Microsoft.Security/pricings, to make the name an optional parameter so we don't need to work around in this way. 

Confirmed using an "empty" array for the bundle parameter appears to have the same result as not deploying Microsoft.Security/pricings 

Will assess the ternary operation in Bicep and if that is feasible or if there is a boolean type expression we can insert to simply opt out if the environment is not AzureUSGovernment or AzureCloud.
