### ISSUE TITLE
Management group creation

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#65]
**Description**
Document the steps required for an end-user to add their subscriptions to a Management Group or create their own.

**Acceptance Criteria**
- ~The deployment creates a management group.~
- ~The management group is created with defaults.~
- ~Subscriptions in the deployment are added to the management group.~
- Document the approach for Management Groups and why they may or may not be a fit next to a Mission LZ deployment

**Comment by brooke-hamilton** [comment]
Need to determine the proper order of operation - does this happen as part of setup or in Terraform

**Comment by sstjean** [comment]
Are we supporting creating that management group as a child of another management group or simply creating it off the Tenant Root?
