### ISSUE TITLE
Investigate Zero Trust TIC 3.0 Workbook items

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#666]
## Benefit/Result/Outcome

As a customer, I want to be able to verify that the Zero Trust Workbook if suitable for my needs, so that I can be confident in my threat analytics posturing and Sentinel dashboard. 

## Description
Azure Sentinel has the Zero Trust (TIC 3.0) workbook. (https://devblogs.microsoft.com/azuregov/zero-trust-in-azure-for-government/). This is a follow-on item for #258 

Additional work will need to be committed to determine the value of deploying a Zero Trust (TIC 3.0) Workbook to Azure Sentinel and if additional configuration is needed. 

## Acceptance Criteria

Determinations are made regarding the suitability of this workbook for customers in meeting their compliance requirements. 
Appropriate cards are chosen and checked by default (or generate new work to determine what this is, or how to implement it via a README)
For findings reported by the workbook, consider whether new backlog items should be created for MLZ. (Some of the findings may require customer intervention based on their preferences/needs.)

**Comment by jamasten** [comment]
PG is no longer maintaining this workbook.  We will look to add other Sentinel automation.
