### ISSUE TITLE
Automated check for copyright header on code files

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#672]
## Benefit/Result/Outcome

So that developers are assured that all code files have consistent and correct copyright headers.

## Description

We have a requirement to have copyright headers on all code files. We currently do it manually, which can lead to some files missing the required header. We would like to have the headers checked and/or added automatically when a PR is created.

A possible implementation is to add this to the SBOM generation pipeline and rename that pipeline to "code-generation". A separate pipeline is also good.

## Acceptance Criteria

- PR automation that checks and/or adds the required copyright header.

**Comment by jamasten** [comment]
duplicate
