### ISSUE TITLE
Document differences between the Bicep and Terraform deployments

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#679]
## Benefit/Result/Outcome

So that a person can easily understand the differences between a Bicep deployment and a Terraform deployment without having to deploy both and compare.

## Description

The Bicep and Terraform deployments result in slightly different implementations of Mission Landing Zone. Having a document that concisely describes the differences will be valuable for people evaluating which one to deploy.

## Acceptance Criteria

A markdown document exists with at least the following sections:

- A description comparing Bicep and Terraform deployments and describing the relative tradeoffs for choosing Bicep or Terraform. (Include a statement about supporting general parity, but Bicep development has priority over new Terraform development.)
- A three column table listing features and true/false checkboxes for Bicep and Terraform implementation, i.e., Feature | Bicep | Terraform

**Comment by brooke-hamilton** [comment]
One could deploy both and then export the json templates to help with the comparison.

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
