### ISSUE TITLE
Customer Question Answer Optimization

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#691]
## Benefit/Result/Outcome

*As a system integrator, I want to receive timely responses to questions I have for Mission LZ so that I can be successful in my implementation of Mission LZ in my cloud environment*

## Description

*We provide an automated way to triage backlog items that have the "question" tag attached*
*One idea, is to auto populate a discussion thread from the backlog item* 
*Another idea is to auto-respond to issues tagged with the question parameter and point them to documentation

## Acceptance Criteria

-  Documentation is created to outline this new process 
- Automation workflow is created to help direct system integrators to get answers more timely

**Comment by brooke-hamilton** [comment]
It's fine for people to post questions in the issues list. The existing automation in GitHub that sends notifications is currently working.
