### ISSUE TITLE
Multiple private link scopes created for same LAWS in MLZ Bicep on re-deployment

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#700]
## Description

When a user deploys a second-time on-top a previous deployment, multiple private link scopes are configured to the same Log Analytics Workspace instead of going un-created by incremental mode/replaced.

My smell is that it has to do with names being "too unique" and being generated on each deployment instead of unique-ish to a deployment:

You can see here the resource names are assigned:

https://github.com/Azure/missionlz/blob/f261f1d92edacde43c035cf6da2512e036c12655/src/bicep/modules/privateLink.bicep#L33-L36

But, that `uniqueData` property is new'd on every deployment:
https://github.com/Azure/missionlz/blob/f261f1d92edacde43c035cf6da2512e036c12655/src/bicep/modules/privateLink.bicep#L21-L22

Instead, it might be good to generate these names at the root `mlz.bicep` and pass it down into the `privateLink.bicep` module so that its uniqueness is unique-ish and preserves idempotency.

## Steps to Reproduce

1.  Deploy Mission LZ
2.  Deploy Mission LZ again with the same deployment name and configuration (say, for example, your first deployment failed)

## Expected behavior

The already existing private link scope is re-used for the second deployment and there is no other private link scope attached to the MLZ Log Analytics Workspace.

## Actual behavior

A second private link scope is created, both attached to the MLZ Log Analytics Workspace

## Additional context

Operating System: n/a
Terraform Version: n/a
Cloud (public, Azure Government, etc.): AzureCloud

**Comment by glennmusa** [comment]
+@mikedzikowski for more details

**Comment by colemanjrNIH** [comment]
My team ran into this issue. Thanks @glennmusa for the write up here and thanks again for talking with our team.
In my discussion with Glenn I confused the point a bit, we had some other errors that made this look inconsistent.
I reverted those changes and can confirm that a new private link scope is created on each deployment. My team's workaround is to hard code the "suffix" and that resolved the issue, we just need to pull this parameter up to the mlz.bicep level as suggested above.


An unrelated, but interesting detail is that the --what-if flag shows all private link scopes. Not sure if this is intended behavior or not.
Screenshot of privateLinkScope resource from --what-if output.
![image](https://user-images.githubusercontent.com/101894300/161337273-4392871b-7736-4866-856a-fa9e29f1bccf.png)

**Comment by brooke-hamilton** [comment]
This is related to #695 - investigating idempotency.

**Comment by BrandonSharp** [comment]
We're running into the same issue of idempotency, and my gut leads me to the same solution that @glennmusa describes above: just up-level the `uniqueData` parameter to the `mlz.bicep` template as a parameter and use the same value on subsequent deploys. 

A similar, possibly more elegant solution, would be to make use of [the uniquestring function](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-string#uniquestring) to create a hashed string based on the subscription/deployment pair. I'm currently experimenting with the following, as an example and will PR it if useful:

```
@description('Data used to append to resources to ensure uniqueness')
param uniqueData string = substring(uniqueString(subscription().subscriptionId, deployment().name), 0, 8)
```

But the other question I have is: *Is uniqueness of name important for these resources at all?*  I can't think of a reason off-hand, but I'm not so arrogant to think I might be missing something. 😄
