### ISSUE TITLE
Requesting network routing changes

### ISSUE THREAD

**Issue by sergio-re** [Azure/missionlz#707]
As per the April 7 MLZ call and discussion, please make the following networking changes to MLZ networking:

**1.** Change the routing tables applied to the spoke VNETs and subnets to not propagate gateway routes.
The reasoning behind this request is to prevent inadvertent routing that bypasses the firewall when a Virtual Network Gateway is added. and Site-to-site connections created. When a site-to-site connection is created and BGP advertisement used, BGP routes are by default automatically advertised to spoke VNETs and subnets and consequently traffic from the spokes automatically bypasses the firewall and goes to the GatewaySubnet and then to on-prem or the S2S connection.
**2.** Add a route to the above route tables ensuring that traffic sent to the jump boxes in the hub VNET and subnet goes through the firewall.
The logic behind this request is to ensure traffic from the spokes going to the jump boxes is forced to go through the firewall. MLZ as configured today allows this traffic to bypass the firewall.
**3.** Add routes to the routing table for the jump box subnet in the hub VNET to forward traffic to the firewall when connecting to the different Tiers, and set propagate gateway routes to **no**.
The logic behind this request is to force traffic from the jump boxes subnet in the hub VNET to not bypass the firewall when going to the spoke VNETs and to also ensure traffic from these servers do not bypass the firewall when sending traffic outside MLZ to a S2S connection if one is created later.
**Bonus request**
Please add a GatewaySubnet subnet in the hub VNET and add a routing table associated with it that is set to propagate gateway routes, and has routes for each and every Tier VNET and the jump boxes subnet in the Hub VNET pointing to forward traffic to the Firewall.
The logic for this request is to ensure that if a Virtual Network Gateway and S2S connections are created later, incoming traffic through the S2S connection(s) and headed to the spoke VNETs will go through the Azure Firewall before going to the spoke VNETs, and avoid inadvertent firewall bypass.

Thanks!

**Comment by brooke-hamilton** [comment]
@sergio-re thank you for this! 🥇

**Comment by jamasten** [comment]
Created sub tasks / issues for this request. Thanks!
