### ISSUE TITLE
Change vnet parameters to allow for multiple subnets

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#710]
## Benefit/Result/Outcome

*As a systems administrator, I would like to be able to configure multiple subnets and addressPrefix parameters in my vnet to allow for future work and ipv6 support 'persona: IT admin'.*

## Description

presently the vnet has one static string value in the vnet for the `subnet` and `addressprefix`, in order to allow for additional subnets and address prefixes we need to change the data type to an array, to allow for systems integrators to add an additional scope (ie: for ipv6).

## Acceptance Criteria

-  `subnet` and `addressprefix` in vnets are changed from a string to an array datatype in bicep
-  `subnet` and `addressprefix` in vnets are changed from a string to an array datatype in terraform

**Comment by lisamurphy-msft** [comment]
This will be considered pre-cursor work as per #693

**Comment by Monte-Hazboun** [comment]
Hi - it looks like this functionality already exists for terraform so just the bicep modules would need to be updated.   I'd like to help take on this update if the work isn't already being done.  Please thumbs up this message if that's ok and I'll submit a PR when the work is done.

**Comment by lisamurphy-msft** [comment]
@Monte-Hazboun this is an open-source project, feel free to take on this issue. 
Thank you in advance!

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
