### ISSUE TITLE
Investigate using Terraform version 2

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#713]
## Benefit/Result/Outcome

So that IT Admins can use the latest version of Terraform.

## Description

We want to investigate the impact of moving to Terraform version 2. The GitHub dependabot submitted a PR for the update, #709, but we want to do more testing, especially in the air-gapped clouds and in Azure Cloud Shell.

Work on this is limited to 16 hours, plus time to test in the air-gapped clouds.

## Possible outcomes (one or more of these)

- We decide to defer updating to TF 2 until support is in place for Azure Cloud Shell and the air-gapped clouds.
- We decide to update to TF 2 now.

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
