### ISSUE TITLE
Tier 3 Does not deploy policy like the mlz.bicep core. 

### ISSUE THREAD

**Issue by LManning-Dev** [Azure/missionlz#731]
## Description
Tier 3 should deploy policy, defaulting to the policy deployed by the mlz.bicep core but as an overwritable parameter

## Steps to Reproduce
deploy mlz.bicep with NIST
deployPolicy=$true `
policy="NIST"

Deploy Tier 3
## Expected behavior
Tier 3 deploys the same policy as the core

## Actual behavior
Tier 3 does not deploy policy

## Additional context

Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.):

**Comment by lisamurphy-msft** [comment]
This was already completed as per: 
https://github.com/Azure/missionlz/pull/728
Closing out this item.
