### ISSUE TITLE
Mission Landing Zone SVG Source Visio

### ISSUE THREAD

**Issue by LManning-Dev** [Azure/missionlz#732]
Would it be possible to get the source Visio that was used to create https://github.com/Azure/missionlz/blob/main/docs/images/20220204_missionlz_as_of_Feb2022_light.svg

It would be helpful to document deployments that follow this model.

Thank you

**Comment by lisamurphy-msft** [comment]
@LManning-Dev I can provide this to you directly via teams; will close out this issue.

**Comment by ClinteRich** [comment]
@lisamurphy-msft  - May I also have a copy of the Visio please?
