### ISSUE TITLE
Additional Azure policy?

### ISSUE THREAD

**Issue by paullizer** [Azure/missionlz#735]
Should we include Azure Security Benchmark?
Should we provide options (check box to option additional menu?) to deploy specific use case Azure policies for
- Allowed regions
- Resource delete lock
- Deny public IP (VMs, storage account, etc.)
- others?

**Comment by lisamurphy-msft** [comment]
* Allowed Regions - MissionLZ strives for parity and deployability in all Azure regions, if you are discovering a specific use case that prevents successful deployment, please reach out and submit a bug report. 
* Resource group delete locks are not included in the MissionLZ baseline, we should provide at the very least a utility that allows for this functionality : will create a backlog item to address this issue. 
* Deny public IP: the firewall in the hub resource group restricts traffic and has a deny all implicit. This is a hub and spoke network that provides for a more secure architecture. 
* others? Not sure what is meant by others but you bring up some great points. For now will create another backlog item for Azure Security Benchmark

**Comment by paullizer** [comment]
> * Allowed Regions - MissionLZ strives for parity and deployability in all Azure regions, if you are discovering a specific use case that prevents successful deployment, please reach out and submit a bug report.
> * Resource group delete locks are not included in the MissionLZ baseline, with the exception of log analytics workspace;  we should provide at the very least a utility that allows for this functionality : will create a backlog item to address this issue.
> * Deny public IP: the firewall in the hub resource group restricts traffic and has a deny all implicit. This is a hub and spoke network that provides for a more secure architecture.
> * others? Not sure what is meant by others but you bring up some great points. For now will create another backlog item for Azure Security Benchmark

Hello, I appreciate your reply but you misunderstood my request. This is around policy deployment that supports those scenarios. These are policy topics that could be deployed alongside Azure Security Benchmark. Right now, you select one policy and only one policy, but many organizations need policies beyond compliance policies. Some examples of policies that many organizations utilize are:
- Allowed Regions
- Resource delete lock
- Deny public IP (like NICs with public IP, or storage accounts with public access, etc.)
- There are many more policies that would be particularly useful to be deployed with MLZ, Im sure others could provide additional examples.

These policies could be selected using check boxes or whichever format works best to provide a smooth and understandable form workflow.

**Comment by paullizer** [comment]
> * Allowed Regions - MissionLZ strives for parity and deployability in all Azure regions, if you are discovering a specific use case that prevents successful deployment, please reach out and submit a bug report.
> * Resource group delete locks are not included in the MissionLZ baseline, with the exception of log analytics workspace;  we should provide at the very least a utility that allows for this functionality : will create a backlog item to address this issue.
> * Deny public IP: the firewall in the hub resource group restricts traffic and has a deny all implicit. This is a hub and spoke network that provides for a more secure architecture.
> * others? Not sure what is meant by others but you bring up some great points. For now will create another backlog item for Azure Security Benchmark

Hello, I appreciate your reply, but you misunderstood my request. This is around policy deployment that supports those scenarios. These are policy topics that could be deployed alongside Azure Security Benchmark. Right now, you select one policy and only one policy, but many organizations need policies beyond compliance policies. Some examples of policies that many organizations utilize are:
- Allowed Regions
- Resource delete lock
- Deny public IP (like NICs with public IP, or storage accounts with public access, etc.)
- There are many more policies that would be particularly useful to be deployed with MLZ 

These policies could be selected using check boxes or whichever format works best to provide a smooth and understandable form workflow.

**Comment by lisamurphy-msft** [comment]
Understood, some of the points made appeared to align with what was already inherent in the design of MLZ. 
We have some policy deployment options, mostly described [here](https://github.com/Azure/missionlz/blob/main/docs/policies.md) as an example. 
As stated, we currently only support the added policies of `NIST`, `IL5`, and `CMMC` which have built in assignments. 
If there is a feature request for another policy, then please let us know and we can put this in our backlog for consideration.

**Comment by paullizer** [comment]
> Understood, some of the points made appeared to align with what was already inherent in the design of MLZ. We have some policy deployment options, mostly described [here](https://github.com/Azure/missionlz/blob/main/docs/policies.md) as an example. As stated, we currently only support the added policies of `NIST`, `IL5`, and `CMMC` which have built in assignments. If there is a feature request for another policy, then please let us know and we can put this in our backlog for consideration.

I appreciate taking the time to discuss and entertain the idea of adding more Azure Policies. It could be great to leverage MLZ beyond providing an amazing infrastructure but also introduce Azure governance with policies that provide operational scalability.

- Allowed regions is an Azure Policy that you deploy that then defines where future resources can be deployed. It is not a configuration of where MLZ is deployed.
- I am not referencing the inbound deny all on the Azure firewall. There are Azure policies that restrict the deployment of future Azure resources like public IP NICs for VMs or public access setting for a storage account. 
- There are more "simple" policies like this that could be slotted into a framework in MLZ. 
- It would be great to add ASB to the list of existing policies like NIST, IL4, and CMMC.
- It would also be great if one or more could be selected instead of only one. If multi-select were provided, then purpose specific policies could be added there too. Otherwise, another section could be created to house them.

I will look at incorporating these into MLZ and submit a PR for you and the team's review.

**Comment by lisamurphy-msft** [comment]
Thank you @paullizer for your due diligence, there is work actively being done per #744 that will further decouple NIST into rev4 and rev5 which is currently being reviewed, but additional policy work is always welcome if it is something you are keen on adding to the policy baseline.
