### ISSUE TITLE
Decouple jumpbox deployment from terraform

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#747]
## Benefit/Result/Outcome

*The bicep deployment of MLZ does not inherently add a jump box VM yet the Terraform deployment does. Having parity in the behaviors of the two deployment types would be a better customer experience*

## Description

*Decouple the jumpbox VM from the main Terraform deployment and provide a utility that allows for adding it on an as-needed basis*

## Acceptance Criteria

-  TBD
-  TBD

**Comment by kyle-hoyer** [comment]
This has been pulled out as a "Remote Access" option during deployment.
