### ISSUE TITLE
Implement Disk Encryption and Secure Boot on Bastion VMs

### ISSUE THREAD

**Issue by chbragg** [Azure/missionlz#774]
Implement an option to use either Azure Disk Encryption or Encryption at Host on the Bastion VMs in the Hub. Also provide an option to use the "Security Type" option of either "Trusted Launch" or "Confidential VM" with vTPM, Secure Boot, and Integrity Monitoring. These two features greatly improve the security of the VMs deployed as part of MLZ.

https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch
https://learn.microsoft.com/en-us/azure/confidential-computing/quick-create-confidential-vm-portal-amd
https://learn.microsoft.com/en-us/azure/virtual-machines/disk-encryption-overview

**Comment by jamasten** [comment]
Server-Side Encryption with Encryption at Host plus Trusted Launch has been added to the bicep code. These are the recommended zero trust configurations that we plan to implement for now.

**Comment by sergio-re** [comment]
You may want to list EncryptionAtHost as a pre-requisite Resource Provider (Microsoft.Compute) for subscriptions or the bicep code will fail.

**Comment by jamasten** [comment]
@sergio-re thanks for the feedback! You are absolutely correct. I will validate our documentation and if that is missing, I will open a bug.
