### ISSUE TITLE
Add Zero Trust Resources on Applicable Resource Types

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#789]
## Benefit/Result/Outcome
Add Private Link and Private DNS Zones to applicable deployed resources - this will increase customer security posture to meet zero trust requirements 

## Description
Add Private Link and Private DNS Zones to applicable deployed resources - this will increase customer security posture to meet zero trust requirements 

## Acceptance Criteria
Add Private Link and Private DNS Zones to applicable deployed resources - this will increase customer security posture to meet zero trust requirements. Reduce public access, etc. 

Key Vaults
Storage Accounts 
Etc. 

-  
-

**Comment by jamasten** [comment]
@mikedzikowski are we missing private link on anything still or can this be closed?

**Comment by jamasten** [comment]
@mikedzikowski closing for now. Please reopen if we missed anything.
