### ISSUE TITLE
azurerm provider warning during terraform init and terraform apply

### ISSUE THREAD

**Issue by jpurban-dt** [Azure/missionlz#792]
## Description

While doing a deploy of completely default MissionLZ using terraform, following the terraform deployment how-to, I receive the following warning:

│ Warning: Reference to undefined provider
│ 
│   on main.tf line 313, in module "hub-network":
│  313:   providers  = { azurerm = azurerm.hub }
│ 
│ There is no explicit declaration for local provider name "azurerm" in module.hub-network, so Terraform is assuming you mean to pass a configuration for "hashicorp/azurerm".
│ 
│ If you also control the child module, add a required_providers entry named "azurerm" with the source address "hashicorp/azurerm".
│ 
│ (and 11 more similar warnings elsewhere)

## Steps to Reproduce

1.  Establish empty subscription
2.  Run the git clone command from the basic how-to
3. Run the terraform init and terraform apply commands per the terraform how-to.

## Expected behavior

Running a completely default test bed should not produce any warnings or errors.

## Actual behavior

The given warning is generated.  Further text suggests it is assuming hashicorp/azurerm and how to explicitly declare this intention if it is the desired provider.

## Screenshots

![image](https://github.com/Azure/missionlz/assets/132471481/5d41089c-fee1-4eb5-bb7b-0a696f7be379)

[Redactions are personally identifying information and/or the subscription ID itself]

## Additional context

Operating System: Azure CLI - Powershell
Terraform Version: 1.3.2 (default provided with the Azure CLI - Powershell environment)
Cloud (public, Azure Government, etc.): public

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
