### ISSUE TITLE
Error in firewall diagnostics during terraform apply

### ISSUE THREAD

**Issue by jpurban-dt** [Azure/missionlz#793]
## Description

When following the terraform deploy how-to using an unedited clone of the repo, the firewall steps fail when creating Monitor Diagnostics.

## Steps to Reproduce

1.  Bring up the Azure CLI in the web interface for Azure.
2.  follow the steps up to the terraform apply step in the terraform deploy.

## Expected behavior

A fully deployed MissionLZ without warning or errors.

## Actual behavior

The process crashes with the following errors:

│ Error: creating Monitor Diagnostics Setting "firewall-fw-diagnostics" for Resource "/subscriptions/[REDACTED SUBSCRIPTION ID]/resourceGroups/mlz-762bb263b05991e0-hub/providers/Microsoft.Network/azureFirewalls/firewall": diagnosticsettings.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Diagnostic settings does not support retention for new diagnostic settings."
│ 
│   with module.firewall.azurerm_monitor_diagnostic_setting.firewall-diagnostics,
│   on ../modules/firewall/main.tf line 90, in resource "azurerm_monitor_diagnostic_setting" "firewall-diagnostics":
│   90: resource "azurerm_monitor_diagnostic_setting" "firewall-diagnostics" {
│ 
╵
╷
│ Error: creating Monitor Diagnostics Setting "firewall-client-public-ip-pip-diagnostics" for Resource "/subscriptions/[REDACTED SUBSCRIPTION ID]/resourceGroups/mlz-762bb263b05991e0-hub/providers/Microsoft.Network/publicIPAddresses/firewall-client-public-ip": diagnosticsettings.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Diagnostic settings does not support retention for new diagnostic settings."
│ 
│   with module.firewall.azurerm_monitor_diagnostic_setting.publicip-diagnostics,
│   on ../modules/firewall/main.tf line 134, in resource "azurerm_monitor_diagnostic_setting" "publicip-diagnostics":
│  134: resource "azurerm_monitor_diagnostic_setting" "publicip-diagnostics" {
│ 

## Screenshots

![image](https://github.com/Azure/missionlz/assets/132471481/0f395b27-f87f-47be-a94c-6b38e9b6c73b)

[Redactions to remove personally identifying information and the subscription ID]

## Additional context

Operating System: Azure CLI - Powershell
Terraform Version: 1.3.2 (default provided with the Azure CLI - Powershell environment)
Cloud (public, Azure Government, etc.): public

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
