### ISSUE TITLE
Add Firewall Option for SKU 

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#794]
## Benefit/Result/Outcome

Add a UI step/element to allow for selecting the Azure Firewall SKU type during a portal driven deployment.

## Description

Remove default parameter and add an option in the UI for MLZ for the Azure Firewall SKU selection. 

## Acceptance Criteria

- Allows users to select firewall SKU for their requirements.

**Comment by jamasten** [comment]
Premium is not available across all our clouds. This issue needs higher prioritization.
