### ISSUE TITLE
Add Zero Trust Imaging to Add-Ons for MLZ to support AVD 

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#797]
## Benefit/Result/Outcome

Add Zero Trust Imaging to Add-Ons for MLZ to support AVD 

## Description

Update the MLZ codebase to support a spoke deployment and support AVD Imaging using the code from the repository here:
https://github.com/mikedzikowski/ZTAImage

## Acceptance Criteria
-  A spoke / tier 3 workload can be deployed optionally as part of MLZ that supports AVD imaging 
-

**Comment by jamasten** [comment]
#833
