### ISSUE TITLE
Tier 3 Add-on: Allow Spoke Communication Firewall Rules need to be idempotent during deployments  

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#800]
## Benefit/Result/Outcome

Allow Spoke Communication Firewall Rules need to be idempotent during deployments  

## Description

The Azure firewall rules that allow spoke communication firewall rules need to be idempotent during deployments so that the rules are not created multiple times if code is ran multiple times 

## Acceptance Criteria

-  Code is idempotent and rules are not duplicated

**Comment by jamasten** [comment]
No longer needed.
