### ISSUE TITLE
MLZ: List of available regulatory compliance policies per cloud

### ISSUE THREAD

**Issue by jayhaddad** [Azure/missionlz#829]
## Benefit/Result/Outcome

Make a list of selectable federal-focused regulatory compliances policies per cloud. Explore selection options with Defender for Cloud Regulatory Compliance and/or Azure Policy

## Description

See attached [regcomplianceid.csv](https://github.com/Azure/missionlz/files/14067112/regcomplianceid.csv)

## Acceptance Criteria

1. Give customer option to deploy via azure policy and/or regulatory compliance - defender for cloud.

**Comment by jamasten** [comment]
@jayhaddad is this still valid? Are we allowed to list the capabilities for policy per cloud? Please close if we can't.
