### ISSUE TITLE
Automated deployments should be uniquely identifiable with tags

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#85]
**Benefit/Result/Outcome**  
Knowing which specific version of MissionLZ was deployed from some automation would benefit development teams and IT Admins.

**Description**
Tags on resources and resource groups will allow IT Admins and support functions to determine which resources were deployed by MLZ and what version of MLZ was used.

**Acceptance Criteria**
- A tag identifies resources deployed by Mission Landing Zone, e.g. "MissionLandingZone"
- Resources deployed via Terraform are distinct from those deployed with Bicep (maybe `MissionLandingZoneTF` or `MissionLandingZoneARM`?)
- Resource groups receive the same tags

**Comment by brooke-hamilton** [comment]
I updated the original text and acceptance criteria to refer to tags instead of resource names.

**Comment by lisamurphy-msft** [comment]
The Terraform portion of this user story is complete
Pending Bicep tagging before resolution

**Comment by lisamurphy-msft** [comment]
re-opening because the bicep tagging is not yet completed

**Comment by lisamurphy-msft** [comment]
opening once again, still need to complete the bicep portion of this user story
