### ISSUE TITLE
Add partner ID for deployment tracking

### ISSUE THREAD

**Issue by jamasten** [Azure/missionlz#871]
https://learn.microsoft.com/en-us/partner-center/marketplace/azure-partner-customer-usage-attribution

**Comment by JCoreMS** [comment]
I'll try to add this for you if you'd like.  In the meantime here is the code:

Just call an empty deployment passing the PID that you create(d)  Just remember that you want to give the users the option to opt out.

param optoutTelemetry bool = false

module deploymentNames_pidCuaDeployment 'modules/pid_cuaid.bicep' =
  if (!optoutTelemetry) {
    name: PidcuaAvdPatternDeploymentName
    params: {}
  }


https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/patterns/avd/templates/modules/pid_cuaid.bicep

**Comment by jamasten** [comment]
ESRI provided their partner ID and will be added for the components that deploy their products.
