### ISSUE TITLE
Adjust sentinel-linked log analytics workspace to 90 days

### ISSUE THREAD

**Issue by jayhaddad** [Azure/missionlz#938]
## Benefit/Result/Outcome

When Sentinel is activated, you get 90 days of included retention. Sentinel-linked workspace should be adjusted to match 90 days retention.

## Description

Adjust hot/online retention to 90 days.

## Acceptance Criteria

-  
-

**Comment by jamasten** [comment]
This issue was fixed with PR https://github.com/Azure/missionlz/pull/941
