### ISSUE TITLE
az what-if and terraform plan PR Validation Checks

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#94]
**Benefit/Result/Outcome**  

Know that proposed changes don't affect a working solution.

**Description**

When a Pull Request is raised, attempt to deploy the source in some known environment, but with unique resources that are destroyed upon success or failure.

This work may depend on #89. 

**Acceptance Criteria**
    - ~~run linter~~ (done already by GitHub Actions)
    - ~~run bicep build/validate~~ (done already by GitHub Actions)
    - ~~run terraform validate~~ (done already by GitHub Action)
    - run bicep az deployment what-if (will be done in AzDevOps, go touch a subscription and a cloud see if a deployment is possible)
    - run terraform plan (will be done in AzDevOps, go touch a subscription and a cloud see if a deployment is possible)

**Comment by brooke-hamilton** [comment]
Not all changes require a full deploy and teardown test. For example, documentation updates and issue templates changes. It would be nice if we could have the automation determine when full deploy is required based on the folder(s) containing the changed files.

**Comment by glennmusa** [comment]
@vidyambala @brooke-hamilton updated the title and acceptance criteria with team decisions
