### ISSUE TITLE
Remove resource lock for workspace

### ISSUE THREAD

**Issue by jayhaddad** [Azure/missionlz#940]
## Benefit/Result/Outcome

Sentinel-linked workspaces cannot have a resource lock. https://learn.microsoft.com/en-us/azure/sentinel/best-practices-workspace-architecture#technical-best-practices-for-creating-your-workspace.

https://learn.microsoft.com/en-us/azure/sentinel/enable-entity-behavior-analytics#prerequisites (This is the feature of sentinel that doesn't like resource locks)

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=json#considerations-before-applying-your-locks

From docs page:

A read-only lock on a Log Analytics workspace prevents User and Entity Behavior Analytics (UEBA) from being enabled.

A cannot-delete lock on a Log Analytics workspace doesn't prevent [data purge operations

## Description
Remove resource lock to ensure workspace falls in line with guidance.

## Acceptance Criteria

-  
-

**Comment by jamasten** [comment]
This fix was implemented with PR #941
