### ISSUE TITLE
Destroy_tf.sh - fails when a given path isn't valid with an unhelpful error.

### ISSUE THREAD

**Issue by sstjean** [Azure/missionlz#96]
**Description**
When running destroy_tf.sh, if the user enters an invalid path, the code breaks with an error from cp.  This doesn't help the user solve the problem.

**Steps to Reproduce**
1. vscode@missionlz-dev:/workspaces/missionlz/build$ ./destroy_tf.sh   ../src/core/mlz_tf_cfg.var   ../src/core/globals.tfvars   ../src/core/saca-hub/saca-hub_test.tfvars   ../src/core/tier-0/tier-0_test.tfvars   ../src/core/tier-1/tier-1_test.tfvars  ../src/core/tier-2/ tier-2_test.tfvars y 

**Expected behavior**
An actionable error message is returned

**Actual behavior**
cp: -r not specified; omitting directory '/workspaces/missionlz/src/core/tier-2'

**Screenshots**

**Additional context**
Operating System:
Terraform Version:
Cloud (public, Azure Government, etc.):

**Comment by brooke-hamilton** [comment]
Added needs triage label because we need to review this issue after Terraform consolidation is complete.

**Comment by brooke-hamilton** [comment]
The clean script fixes this issue.
