### ISSUE TITLE
MLZ: Optional deploy a different flavor of Linux for Bastion Jump Host

### ISSUE THREAD

**Issue by mikedzikowski** [Azure/missionlz#977]
## Benefit/Result/Outcome

Optional deploy a different flavor of Linux for Bastion Jump Host

## Description

Optional deploy a different flavor of Linux for Bastion Jump Host

## Acceptance Criteria

-  Optional deploy a different flavor of Linux for Bastion Jump Host

**Comment by tsweatman1** [comment]
@jamasten, looking for clarification on this.  Do we want to offer multiple Linux version, ie RH, Debian and Ubuntu or just update the version of Ubuntu?  The default was 18.04 LTS but it has been changed to 20_04 already.
