### ISSUE TITLE
Retry Flags

### ISSUE THREAD

**Issue by Breanna-Stryker** [Azure/missionlz#98]
**Is your feature request related to a problem? Please describe.**
Azure doesn't exhibit deterministic behaviors.  Frequently different portions of script roll outs fail and the system needs to be retried.  This has occurred when creating keyvaults, registries/container instances, etc.   At this point the script will fail since part of the roll out has been created. 

**Describe the solution you'd like**
We should add a retry flag for users.   If the retry flag is present the script doesn't fail, it continues to run with with the options that have already been created instead. 

**Describe alternatives you've considered**
Alternatives could be if any point of the script fails, a hard roll back is performed permanently deleting all of the items to let the user retry again.

**Comment by brooke-hamilton** [comment]
We should take another look at this after Terraform consolidation is done. Some possible needs include: clean up a failed deployment, retry an existing deployment, and idempotent deployments.

**Comment by glennmusa** [comment]
+1 to idempotency

@Breanna-Stryker brings up good points about checking the Service Principal ownership instead of creating one net-new

**Comment by brooke-hamilton** [comment]
This issue is now covered by reusing service principals and having a single Terraform deployment.
